#NoEnv
#SingleInstance force
; send the corrected word on reload (will replace the selected word)

if(%0% > 1)
    Send, %2%
; a tiny GUI setup
Gui, Add, Edit, vfrom w200  ,%Hotstring%::
Gui, Add, Edit, vto  w200 ym0,%Hotstring%
Gui, Add, Button, Default, OK
#H::
	AutoTrim Off  
	ClipboardOld = %ClipboardAll%
	Clipboard =  
	Send ^c
	ClipWait 3
	if ErrorLevel  
		return
	StringReplace, Hotstring, Clipboard, ``, ````, All  
	StringReplace, Hotstring, Hotstring, `r`n, ``r, All
	StringReplace, Hotstring, Hotstring, `n, ``r, All
	StringReplace, Hotstring, Hotstring, %A_Tab%, ``t, All
	StringReplace, Hotstring, Hotstring, `;, ```;, All
	
	; trim the word (better imo)
	Hotstring :=  Trim(Hotstring)
	
	Clipboard = %ClipboardOld% 
	
	; setting the hotstrings in the GUI
	GuiControl,, to, %Hotstring%
	GuiControl,, from, %Hotstring%::
	
	; focus to the "to" gui
	GuiControl, Focus, to
	Gui, Show
	
	; send control + a in order toselecctthe text in the "to" gui (better imo)
	Send, ^a
return

; happens when pressing the OK button
ButtonOK:
    ; assembling the hotstring and save it to this file
    GuiControlGet, to
    GuiControlGet, from
    Hotstring := "::" from to
    FileAppend, `n%Hotstring%, %A_ScriptFullPath%  

    ; special reload statement with the word in the "to" gui
    Run, %A_ScriptFullPath% /restart %to%

    Sleep 200
    MsgBox, 4,, The hotstring just added appears to be improperly formatted.  Would you like to open the script for editing? Note that the bad hotstring is at the bottom of the script.
    IfMsgBox, Yes, Edit
return
::dośc::dość
::specjalizacij::specjalizacij
::rozpoczęćie::rozpoczęcie
::spotkalem::spotkałem
::zolw::żółw
::coz::cóż
::lucja::łucja 
::wyglad::wygląd
::zajmowac::zajmować
::zauwazyć::zauważyć
::znajdue::znajduje
::Lte::LTE
::LtE::LTE
::urządzenei::urządzenie
::zdjęćie::zdjęcie
::smarton::smartfon
::dlatego jeśli::dlatego, jeśli
::móże::może
::pojawic::pojawić
::Sim::SIM
::rodzielczości::rozdzielczości
::cyz::czy
::pamięc::pamięć
::miesiąć::miesiąc
::sprobowała::spróbowała
::zydów::żydów
::tzry::trzy
::opróćz::oprócz
::różnia::różnią
::resturacji::restauracji
::tobą::Tobą
::współpracowąć::współpracować
::twój::Twój
::ty::Ty
::jeśi::jeśli
::możliwosci::możliwości
::sie::się
::tłumaczneie::tłumaczenie
::nei::nie
::lekcewarzenie::lekceważenie
::tażę::także 
::pamietaj::pamiętaj
::obsługiwac::obsługiwać
::będa::będą
::dotyczyc::dotyczyć
::korzytsa::korzysta
::tłumaczneia::tłumaczenia
::większośc::większość
::ise::się
::ktorzy::którzy
::mozesz::możesz
::sa::są
::tlumacza::tłumacza
::korzyśći::korzyści
::tekstow::tekstów
::strone::stronę
::teksów::tekstów
::jednie::jedynie
::obrazkow::obrazków
::utrudniaja::utrudniają
::uwage::uwagę
::konsekwetny::konsekwentny
::żę::że
::mozna::można
::uslug::usług
::myślec::myśleć
::moga::mogą
::wyglada::wygląda
::klientow::klientów
::ucza::uczą
::tlumaczenia::tłumaczenia
::wiadomośći::wiadomości
::tlumaczeniowych::tłumaczeniowych
::korzyśc::korzyść
::na prawdę::naprawdę
::błedu::błędu
::jesli::jeśli
::komunikowac::komunikować
::tłumaczen::tłumaczeń
::powstaly::powstały
::transkrybcji::transkrypcji
::usługe::usługę
::powyzszych::powyższych
::nalezy::należy
::Jpg::JPG
::mozę::może
::ksiązki::książki
::zycie::życie
::zaangazowania::zaangażowania 
::mżna::można
::zrobic::zrobić
::angazowany::angażowany
::przykladowo::przykładowo
::ilośc::ilość
::zaangazowany::zaangażowany
::obsluga::obsługa
::musza::muszą
::wiekszą::większą
::współpracuja::współpracują
::możliwośc::możliwość
::najwiekszych::największych
::Crm::CRM
::ktory::który
::polegaja::polegają
::szczerze mówiąc::@@
::DtP::DTP
::zajmuja::zajmują
::zamowić::zamówić
::treśc::treść
::isę::się
::pomoga::pomogą
::zaoferowac::zaoferować
::któe::które
::fikusnych::fikuśnych
::korzystac::korzystać
::czionka::czcionka
::Pdf::PDF
::styli::stylów
::zalezy::zależy
::podejmowac::podejmować
::oddac::oddać
::móżna::można
::przetlumaczyć::przetłumaczyć
::umiejętnośc::umiejętność
::moga::mogą
::zlecen::zleceń
::powinienes::powinieneś
::nauke::naukę
::dotyczace::dotyczące
::pytac::pytać
::umiejętnosci::umiejętności
::jezykowe::językowe
::szybcije::szybciej
::właściwosci::właściwości
::wchodza::wchodzą
::mase::masę
::odchudzaja::odchudzają
::zwieksza::zwiększa
::mase::masę
::mieśni::mięśni
::wydawac::wydawać
::przyjmowac::przyjmować
::dokladne::dokładne
::połaczenie::połączenie
::mięsnie::mięśnie
::miesnie::mięśnie
::rozwinąc::rozwinąć
::zwiekszenie::zwiększenie
::olim::olimp
::mieśniową::mięśniową
::znacznei::znacznie
::tkże::także
::dzęki::dzięki
::źródlo::źródło
::wspomoze::wspomoże
::takżę::także
::mieśniach::mięśniach
::ukladu::układu
::az::aż
::wydolnośc::wydolność
::przyswalajnej::przyswajalnej
::napojow::napojów
::pojemnosci::pojemności
::mieśni::mięśni
::duze::duże
::kóre::które
::kofeine::kofeinę
::odzywki::odżywki
::takze::także
::ktore::które
::żywnośc::żywność
::nalezy::należy
::zakwaszenei::zakwaszenie
::buduja::budują
::będize::będzie
::zaczał::zaczął
::pomoze::pomoże
::zacząl::zaczął
::przycyznia::przyczynia
::nieporządanymi::niepożądanymi
::nia::nią
::dolegliwosci::dolegliwości
::bedize::będzie
::odziezy::odzieży
::dzialanie::działanie
::niebezpieczenstwie::niebezpieczeństwie
::niepożadanych::niepożądanych
::męzczyzn::mężczyzn
::ukladem::układem
::kazdego::każdego
::zapytac::zapytać
::duzo::dużo
::umowić::umówić
::bede::będę
::mógl::mógł
::zapoznal::zapoznał
::zmniejszyla::zmniejszyła
::powierdza::potwierdza
::któa::która
::przeszla::przeszła
::odzywiają::odżywiają
::zmienilo::zmieniło
::zycia::życia
::mężćzyzna::mężczyzna
::szkodza::szkodzą
::wazył::ważył
::jednoczesnie::jednocześnie
::leczenei::leczenie
::poznala::poznała
::przeczytac::przeczytać
::a nad to::a nadto
::a nóż::a nuż
::a pro po::A propos
::absorbcja::absorpcja
::absorbcji::absorpcji
::ad.::ad
::aleji::alei
::alternatywana::alternatywna
::aż nad to::aż nadto
::badz::bądź
::badź::bądź
::bądx::bądź
::bede::będę
::bedę::będę
::bedzie::będzie
::bedziecie::będziecie
::bedziemy::będziemy
::bedziesz::będziesz
::będa::będą
::biegnął::biegł
::biegnęli::biegli
::biegnęła::biegła
::biegnęło::biegło
::bierząco::bieżąco
::bieze::bierze
::bieże::bierze
::biznes plan::biznesplan
::bratowi::bratu
::brożka::broszka
::brut::brud
::byc::być
::byl::był
::byla::była
::bylem::byłem
::byliscie::byliście
::bylismy::byliśmy
::bylo::było
::byly::były
::chart ducha::hart ducha
::chba::chyba
::chłopcowi::chłopcu
::chłopowi::chłopu
::chor::chór
::chyab::chyba
::cibie::ciebie
::cieżarówka::ciężarówka
::co i róż::co rusz
::co nie co::co nieco
::co nie miara::co niemiara
::codzień::co dzień
::conajmniej::co najmniej
::coprawda::co prawda
::cudzysłowia::cudzysłowu
::cudzysłowiu::cudzysłowie
::czegos::czegoś
::czesc::część
::czesta::częsta
::czeste::częste
::czesto::często
::czesty::częsty
::czestych::częstych
::czetry::cztery
::częsci::części
::częśc::część
::czyms::czymś
::d/s::ds.
::dla czego::dlaczego
::dla tego że::dlatego że
::dla tego żeby::dlatego żeby
::dlatego bo::bo
::do nie dawna::do niedawna
::do niech::do nich
::do okoła::dookoła
::do póki::dopóki
::do póty::dopóty
::do tych czas::dotychczas
::dobzre::dobrze
::doczynienia::do czynienia
::dokumnety::dokumenty
::domniemuje::domniemywa
::domniemujesz::domniemywasz
::domniemuję::domniemywam
::dosc::dość
::dosiego::do siego
::dostawają::dostają
::dostep::dostęp
::dosyc::dosyć
::dozowolone::dozwolone
::dróżba::drużba
::drzem::dżem
::drzemy::dżemy
::duł::dół
::duzo::dużo
::dwa kroć::dwakroć
::dzialalności::działalności
::działac::działać
::dzieciami::dziećmi
::dzis::dziś
::dzisiej::dzisiaj
::dziubek::dzióbek
::dzwiek::dźwięk
::dżwięk::dźwięk
::ecru::écru
::ekri::écru
::fekalii::fekaliów
::gdyz::gdyż
::gdzie nie gdzie::gdzieniegdzie
::genitalii::genitaliów
::glos::głos
::głownie::głównie
::głowny::główny
::hab::hab.
::histori::historii
::Hong Kong::Hongkong
::hukło::huknęło
::ię::się
::iloci::ilości
::ilośc::ilość
::imie::imię
::informcje::informacje
::itd::itd.
::itp::itp.
::iwem::wiem
::j.w.::jw.
::jakąs::jakąś
::jakies::jakieś
::jakis::jakiś
::jescze::jeszcze
::jesli::jeśli
::jeszzce::jeszcze
::jezeli::jeżeli
::jezyk::język
::jezyka::języka
::jezyku::języku
::juz::już
::k/::k.
::Ka-ce::Katow.
::kalumni::kalumnii
::kims::kimś
::klineta::klienta
::klinięcie::kliknięcie
::klinij::kliknij
::kocy::koców
::kogos::kogoś
::koleji::kolei
::korzystac::korzystać
::kórz::kurz
::ksiązka::książka
::książe::książę
::ktora::która
::ktorego::którego
::ktorej::której
::ktory::który
::ktorych::których
::ktorzy::którzy
::któa::która
::któe::które
::któy::który
::lbu::lub
::leprze::lepsze
::lini::linii
::lubieć::lubić
:: =łacznie::łącznie
::łać.::łac.
::m. in.::m.in.
::m.in::m.in.
::maił::miał
::mase::masę
::mass-media::mass media
::mażę o::marzę o
::męzczyzna::mężczyzna
::męzczyzny::mężczyzny
::Mężcyzna::Mężczyzna
::miec::mieć
::miedzy::między
::miejsce zamieszania::miejsce zamieszkania
::mieśni::mięśni
::między czasie::międzyczasie
::mięsni::mięśni
::milosc::miłość
::mimo, iż::mimo iż
::mimo, że::mimo że
::moga::mogą
::mogła by::mogłaby
::moj::mój
::mowic::mówić
::mowić::mówić
::moze::może
::mozna::można
::moznaby::można by
::możnaby::można by
::mógł by::mógłby
::musza::muszą
::musze::muszę
::na dal::nadal
::na niech::na nich
::na poziome::na poziomie
::na prawdę::naprawdę
::na przeciw::naprzeciw
::na przeciwko::naprzeciwko
::na raz::naraz
::na tych miast::natychmiast
::na w pół::na wpół
::na wzajem::nawzajem
::nad zwyczaj::nadzwyczaj
::nadzieji::nadziei
::najczęsciej::najczęściej
::najwiecej::najwięcej
::nalezy::należy
::napewno::na pewno
::naprawde::naprawdę
::naprzemian::na przemian
::naprzykład::na przykład
::narazie::na razie
::nast::nast.
::nastepna::następna
::nastepne::następne
::nastepni::następni
::nastepnie::następnie
::nastepny::następny
::nastepnych::następnych
::natomist::natomiast
::nei::nie
::nie musze::nie muszę
::nie omal::nieomal
::nie opodal::nieopodal
::niecałkiem::nie całkiem
::nielada::nie lada
::niema::nie ma
::niemożna::nie można
::nietylko::nie tylko
::niewolno::nie wolno
::niezawsze::nie zawsze
::niz::niż
::nmie::mnie
::nr.::nr
::o prócz::oprócz
::od niech::od nich
::odpowiedż::odpowiedź
::odrazu::od razu
::okres czasu::czas
::okresie czasu::czasie
::oprocz::oprócz
::organiźmie::organizmie
::orginalny::oryginalny
::osobą trzecim::osobom trzecim
::oto chodzi::o to chodzi
::oto chodziło::o to chodziło
::otrzymywac::otrzymywać
::p.n.e::p.n.e.
::p.n.e..::p.n.e.
::p.w.::pw.
::pare::parę
::pażdziernik::październik
::pażdziernika::października
::piatek::piątek
::pne::p.n.e.
::po kątem::pod kątem
::po między::pomiędzy
::po mimo::pomimo
::po nad::ponad
::po nadto::ponadto
::po pod::popod
::po porostu::po prostu
::po przez::poprzez
::po środku::pośrodku
::po woli::powoli
::po za::poza
::pobież::pobierz
::poczatku::początku
::poczym::po czym
::pod katem::pod kątem
::podczas, gdy::podczas gdy
::pojecia::pojęcia
::pojecie::pojęcie
::pojedyńcza::pojedyncza
::pojedyńcze::pojedyncze
::pojedyńczego::pojedynczego
::pojedyńczej::pojedynczej
::pojedyńczy::pojedynczy
::pojedyńczych::pojedynczych
::pokarz::pokaż
::pokolei::po kolei
::pokryjomu::po kryjomu
::pokuj::pokój
::pomimo, iż::pomimo iż
::pomimo, że::pomimo że
::ponad to::ponadto
::poniewaz::ponieważ
::poprawila::poprawiła
::poprostu::po prostu
::porzadek::porządek
::posiadaja::posiadają
::posrod::pośród
::poszłem::poszedłem
::pot wpływem::pod wpływem
::pozatym::poza tym
::pożądek::porządek
::pożądkiem::porządkiem
::pożądku::porządku
::póżniej::później
::pracowal::pracował
::prez::przez
::prof::prof.
::prosba::prośba
::prosze::proszę
::prpopzucja::propozycja
::pryz::przy
::przecierz::przecież
::przed pokój::przedpokój
::przed wczoraj::przedwczoraj
::przede dniu::przededniu
::przedewszystkim::przede wszystkim
::przekonywujący:: przekonywający
::przyjażń::przyjaźń
::przyklad::przykład
::pzrez::przez
::raz wraz::raz w raz
::rąby::romby
::rowniez::również
::rownież::również
::rozdzielczośc::rozdzielczość
::rozdzielczośći::rozdzielczości
::rozumię::rozumiem
::rozwoj::rozwój
::rożno::rożen
::rónież::również
::równierz::również
::równiez::również
::rządana::żądana
::rządane::żądane
:: =rządania::żądania
::rządanie::żądanie
::rządany::żądany
::rzeczywiscie::rzeczywiście
::sa::są
::samochod::samochód
::samodzienie::samodzielnie
::sciśle::ściśle
::sei::się
::sie::się
::sierpien::sierpień
::sklada::składa
::skladaja::składają
::skladają::składają
::skladano::składano
::sobię::sobie
::sp-nia::spółdz.
::spowrotem::z powrotem
::sprawdzila::sprawdziła
::stabilnośći::stabilności
::standart::standard
::struj::strój
::styczen::styczeń
::styli::stylów
::sytem::system
::sytemie::systemie
::sytemu::systemu
::tak na prawdę::tak naprawdę
::takze::także
::takżę::także
::tam tędy::tamtędy
::tournee::tournée
::trzcionka::czcionka
::trzy kroć::trzykroć
::tu dzież::tudzież
::twoj::twój
::tym czasem::tymczasem
::tysięce::tysiące
::tyś.::tys.
::tzreba::trzeba
::umię::umiem
::v-ce::wice
::vzęsto::często
::w brew::wbrew
::w cale::wcale
::w jak sposób::w jaki sposób
::w koło::wkoło
::w krótce::wkrótce
::w linię::w linie
::w między czasie::w międzyczasie
::w niwecz::wniwecz
::w odróżnieniu do::w odróżnieniu od
::w ogule::w ogóle
::w oka mgnieniu::w okamgnieniu
::w okół::wokół
::w pław::wpław
::w pośród::wpośród
::w pół do::wpół do
::w przeciwieństwie od::w przeciwieństwie do
::w raz z::wraz z
::w skutek::wskutek
::w śród::wśród
::w tak sposób::w taki sposób
::w tedy::wtedy
::w/g::wg
::warzy::waży
::wciaz::wciąż
::wciaż::wciąż
::wedlug::według
::Wewnętrza::Wewnętrzna
::wg.::wg
::wgłąb::w głąb
::wiec::więc
::wiecej::więcej
::wiedze::wiedzę
::wiekszą::większą
::wieksze::większe
::wiekszego::większego
::wiekszej::większej
::wiekszosc::większość
::wiekszosci::większości
::wiekszośc::większość
::wiekszości::większości
::wiekszość::większość
::wiekszy::większy
::wiekszych::większych
::wiekszym::większym
::wiekszymi::większymi
::wiele kroć::wielekroć
::wieżę w::wierzę w
::wieży w::wierzy w
::wkoło Macieju::w koło Macieju
::wlasciwosci::właściwości
::wlasnie::właśnie
::własnie::właśnie
::wogle::w ogóle
::wogóle::w ogóle
::wogule::w ogóle
::wokol::wokół
::wowczas::wówczas
::wplyw::wpływ
::wraz tym::wraz z tym
::wrzesnia::września
::wspołczesne::współczesne
::wspomieć::wspomnieć
::wsród::wśród
::wszech obecny::wszechobecny
::wszechczasów::wszech czasów
::wszytkich::wszystkich
::wszytkie::wszystkie
::wszytkim::wszystkim
::wszytko::wszystko
::wszytskich::wszystkich
::wszytskie::wszystkie
::wszytskim::wszystkim
::wszytsko::wszystko
::wyłacznie::wyłącznie
::wymyśleć::wymyślić
::wywolana::wywołana
::wywolane::wywołane
::wzamian::w zamian
::wzdłóż::wzdłuż
::wzgledu::względu
::wziąść::wziąć
::wziąźć::wziąć
::wzięłem::wziąłem
::wzystko::wszystko
::z dużej litery::dużą literą
::z goła::zgoła
::z małej litery::małą literą
::z nad::znad
::z niech::z nich
::z po między::spomiędzy
::z pod::spod
::z pomiędzy::spomiędzy
::z pośród::spośród
::z powody::z powodu itp.
::z poza::spoza
::z przed::sprzed
::z resztą::zresztą
::z wielkiej litery::wielką literą
::z za::zza
::za miast::zamiast
::za nad to::zanadto
::za nadto::zanadto
::za raz::zaraz
::za równo::zarówno
::za zwyczaj::zazwyczaj
::zaden::żaden
::zdechnął::zdechł
::zemną::ze mną
::ziemii::ziemi
::Złodzej::Złodziej
::znaleść::znaleźć
::znowóż::znowuż
::znajdizesz::znajdziesz
::zostal::został
::zpoza::spoza
::zwiazek::związek
::zwiazku::związku
::zwlaszcza::zwłaszcza
::zycie::życie
::żadaj::żądaj
::żadko::rzadko
::żle::źle
::żródło::źródło
::mogla::mogła
::powazny::poważny
::stosowac::stosować
::zajecia::zajęcia
::musiala::musiała
::zobaczyla::zobaczyła
::powiedzial::powiedział
::czerpałą::czerpała
::roznia::różnią
::styli::stylów
::fir::firm
::sa::są
::rodzielczość::rozdzielczość
::lenovo::Lenovo
::rozdzielczośc::rozdzielczość
::sie::się
::ram::RAM
::pozostale::pozostałe
::wyposazony::wyposażony
::qua::Qualcomm Snapdragon
::korzytania::korzystania
::damaszku::Damaszku
::diabel::diabeł
::wzgledów::względów
::łacząca::łącząca
::shashuka::shakshuka
::potarwy::potrawy
::cukini::cukinii
::dodakiem::dodatkiem
::grilowanym::grillowanym
::rozwiazać::rozwiązać
::wiąze::wiąże
::nałożyc::nałożyć
::znacnzie::znacznie
::sharon::Sharon
::myśla::myślą
::męza::męża
::sę::się
::odchudzala::odchudzała
::jje::jej
::odpoczywac::odpoczywać
::zauwazyła::zauważyła
::chca::chcą
::częsciej::częśćiej
::zmienic::zmienić
::spotykac::spotykać
::poczula::poczuła
::znow::znów
::dbac::dbać
::jje::jej
::natomiat::natomiast
::przygotowala::przygotowała
::czesto ::często
::zaczeła::zaczęła
::wydawalo::wydawało
::nieporządane::niepożądane
::dodawala::dodawała
::maslo::masło
::migdalowym::migdałowym
::częśćiej::częściej
::ilosć::ilość
::wazywa::warzywa
::energi::energii
::ktorą::którą
::rozprzestrzenic::rozprzestrzenić
::odzywiał::odżywiał
::mysli::myśli
::okazalo::okazało
::zainteresowac::zainteresować
::napiecie::napięcie
::metode::metodę
::badzo::bardzo
::powrociły::powróciły
::szukac::szukać
::reagowac::reagować
::bardoz::bardzo
::chorowala::chorowała
::kązdy::każdy
::diete::dietę
::zadomowila::zadomowiła
::watróbka::wątróbką
::mimo to,::mimo to 
::swoj::swój
::lepije::lepiej
::zauwazył::zauważył
::zmiane::zmianę
::znalazla::znalazła
::glowa::głowa
::koncu::końcu
::węglowodanow::węglowodanów
::zastosownaie::zastosowanie
::poprosze::poproszę
::czlowiekiem::człowiekiem
::tez::też
::calkowicie::całkowicie
::dzięsiątki::dziesiątki
::załozy::założy
::zaczela::zaczęła
::zamaist::zamiast
::mieśniami::mięśniami
::mozemy::możemy
::osiągnieciu::osiągnięciu
::stabilnośc::stabilność
::wazne::ważne
::montazu::montażu
::umiesczonymi::umieszczonymi
::móżesz::możesz
::sa::są
::pomoca::pomocą
::najbardziej korzystnych::najkorzystniejszych
::męśżczyzna::mężczyzna
::zdecydowal::zdecydował
::polecila::poleciła
::najwiekszym::największym
::myslał::myślał
::mnostwo::mnóstwo
::brala::brała
::używac::używać
::pochodzacy::pochodzący
::schudnąc::schudnąć
::zyciu::życiu
::jedynei::jedynie
::mial::miał
::nastroj::nastrój
::udalo::udało
::dawalo::dawało
::ktorym::którym
::przełozyło::przełożyło
::brac::brać
::sięgneła::sięgnęła
::cos::coś
::ksiażce::książce
::nawiązuja::nawiązują
::dzięsięć::dziesięć
::przykladem::przykładem
::Kaliforni::Kalifornii
::wpadl::wpadł
::umysl::umysł
::róznych::różnych
::zastanow::zastanów
::realizowac::realizować
::przyjemnośc::przyjemność
::srodkami::środkami
::sposob::sposób
::pomysl::pomysł
::sposród::spośród
::ustalic::ustalić
::najwazniejszym::najważniejszym
::koniecznosć::konieczność
::wymyśleć::wymyślić
::musial::musiał
::prowadze::prowadzę
::dac::dać
::drązymy::drążymy
::wykorzytywano::wykorzystywano
::robia::robią
::neizbędne::niezbędne
::oczywiśćie::oczywiście
::najwazniejszych::najważniejszych
::żoładkowych::żołądkowych
::skłądników::składników
::najlatwiejszych::najłatwiejszych
::będe::będę
::pięc::pięć
::możn::można
::Lolipop::Lollipop
::jakoscią::jakością
::róznica::różnica
::tlumaczenia::tłumaczenia
::chetnie::chętnie
::jakosci::jakości
::mozliwości::możliwości
::pomagaja::pomagają
::namowić::namówić
::zamowic::zamówić
::tlumaczenie::tłumaczenie
::zamowią::zamówią
::tłumacyz::tłumaczy
::zamowienia::zamówienia
::jakośc::jakość
::kazdym::każdym
::własciwego::właściwego
::poslugiwanie::posługiwanie
::niezaleznie::niezależnie
::waznych::ważnych
::zbieżnośc::zbieżność
::duza::duża
::okreslonym::określonym
::tlumaczenia::tłumaczenia
::malo::mało
::odłozył::odłożył
::wiadomośc::wiadomość
::zwróc::zwróć
::tlumacz::tłumacz
::wynikaja::wynikają
::błedy::błędy
::wzgledem::względem
::wygladała::wyglądała
::źródlowy::źródłowy
::tlumaczeń::tłumaczeń
::kazdy::każdy
::zamow::zamów
::wpływaja::wpływają
::ciągly::ciągły
::pewnośc::pewność
::mieśnie::mięśnie
::Uniwersal::Universal
::Aminal::Animal
::mięsniową::mięśniową
::Uniwersal::Universal
::mieśniowej::mięśniowej
::osiągnąc::osiągnąć
::kótra::która
::substnacji::substancji
::tkóre::które
::mięsniowych::mięśniowych
::mięsniowych::mięśniowych
::mięsniom::mięśniom
::najwazniejszą::najważniejszą
::jesli::jeśli
::cześćiowy::częściowy
::częśćiowy::częściowy
::płątnym::płatnym
::publicznośći::publicznośCi
::zę::że
::jestes::jesteś
::większosći::większości
::szczęśćie::szczęście
::najczęśćiej::najczęściej
::dopuki::dopóki
::skłądzie::składzie
::mieśniom::mięśniom
::połaczeniu::połączeniu
::bialek::białek
::miesni::mięśni
::śa::są
::mieśniowa::mięśniowa
::dostepny::dostępny
::mięsniowej::mięśniowej
::srodka::środka
::cieszyc::cieszyć
::ćwicza::ćwiczą
::zabrac::zabrać
::dłuzej::dłużej
::mięsniom::mięśniom
::dotycza::dotyczą
::swiadczenie::świadczenie
::złożyc::złożyć
::zaczeli::zaczęli
::tlumaczeniowa::tłumaczeniowa
::kazdego::każdego
::tworzylo::tworzyło
::tworza::tworzą
::większośc::większość
::najwazniejsze::najważniejsze
::najwazniejsze::najważniejsze
::prędkośc::prędkość
::najwazniejszych::najważniejszych
::indiach::Indiach
::pochodza::pochodzą
::zapoznac::zapoznać
::jezyków::języków
::mozliwosć::możliwość
::tlumaczenia::tlumaczenia
::tysiecy::tysięcy
::jakóść::jakość
::uwazają::uważają
::urzadzenia::urządzenia
::wpłynąc::wpłynąć
::wpływaja::wpływają
::wzięly::wzięły
::przypomniec::przypomnieć
::zastapić::zastąpić
::działaja::działają
::znaleźc::znaleźć
::chesz::chcesz
::zaangazuj::zaangażuj
::dopisac::dopisać 
::odnosza::odnoszą
::zagrac::zagrać
::wartośc::wartość
::uslugi::usługi
::rozwiązywac::rozwiązywać
::reklame::reklamę
::zaangazujesz::zaangażujesz
::zdolnośc::zdolność
::wazniejsze::ważniejsze
::błedem::błędem
::mozliwość::możliwość
::najcześciej::najcześciej
::wplywają::wpływają
::firme ::firmę
::wypuntowanych::wypunktowanych
::pytaja::pytają
::różne::różne
::zachowac::zachować
::...::…
::zajmuja::zajmują
::wazniejszy::ważniejszy
::osiągnąc::osiągnąć
::dostala::dostała
::wyglądala::wyglądała
::jezyki::języki
::storny::strony
::przełumaczyło::przetłumaczyło
::zaangazowanie::zaangażowanie
::zaangazowanie::zaangażowanie
::moze::może
::stornę::stronę
::storna::strona
::maszyne::maszynę
::maszyne::maszynę
::służyc::służyć
::jezykową::językową
::mialo::miało
::wystarczajaco::wystarczająco
::zastapią::zastąpią
::jakóśc::jakość
::zagrozonych::zagrożonych
::większośc::większość
::częśći::części
::stornie::stronie
::najwazniejszymi::najważniejszymi
::marta::Marta
::pieniedzy::pieniędzy
::złosliwego::złosliwego
::zamowił::zamówił
::będac::będąc
::polsce::Polsce
::pracuja::pracują
::pokazywac::pokazywać
::jesli::jeśli
::póxno::późno
::okreslonej::określonej
::pisalismy::pisaliśmy
::ksiązek::książek
::dostepne::dostępne
::będa::będą
::zaanwansowanego::zaawansowanego
::radza::radzą
::chca::chcą
::jęśli::jęśli
::zamówic::zamówić
::zamowily::zamówiły
::najwazniejszego::najważniejszego
::rozwiazań::rozwiązań
::powiekszały::powiększały
::wyspecjalizowac::wyspecjalizować
::stalo::stało
::storn::stron
::wywiazywało::wywiązywało
::polacy::Polacy
::tlumaczysz::tłumaczysz
::zgloszeń::zgłoszeń
::mnóśtwo::mnóstwo
::najwieksze::największe
::dzien::dzień
::najwążniejszej::najważniejszej
::zgodnei::zgodnie
::zamowią::zamówią
::zaplaci::zapłaci
::dizeki::dzięki
::okreslony::określony
::wysyłac::wysyłać
::jęśli::jeśli
::kleinta::klienta
::bierzących::bieżących
::baze::bazę
::usunąc::usunąć
::otrzymac::otrzymać
::tworzyc::tworzyć
::sa::są
::tkóry::który
::częśc::część
::trudnośc::trudność
::ominąc::ominąć
::znakow::znaków
::zalożyć::założyć
::najwążniejszych::najważniejszych
::jakas::jakaś
::najgroszych::najgorszych
::myslisz::myślisz
::móżliwośc::możliwość
::większośc::większość
::sprawdzac::sprawdzać
::uzywają::używają
::duzy::duży
::szczególy::szczegóły
::łumaczeń::tłumaczeń
::czesto::często
::tęż::też
::odrywac::odrywać
::teks::tekst
::zostala::została
::urzadzenie::urządzenie
::częśto::często
::polaków::Polaków
::uniknac::uniknąć
::moglaby::mogłaby
::osob::osób
::zwróca::zwrócą
::twojej::Twojej
::twoja::Twoja
::twoje::Twoje
::będizesz::będziesz
::cię::Cię
::firme::firmę
::zdjęćia::zdjęcia
::caly::cały
::posiadal::posiadał
::rozdzielczośćią::rozdzielczością
::najwazniejszy::najważniejszy
::wyposazona::wyposażona
::pamiecią::pamięcią
::przetlumaczeniu::przetłumaczeniu
::twojego::Twojego
::doswiadczenia::doświadczenia
::calości::całości
::czytelnikow::czytelników
::pomiedzy::pomiędzy
::rządają::żądają
::tlumaczeniowym::tłumaczeniowym
::jakóścią::jakością
::rząda::żąda
::namowienie::namówienie
::tlumaczeń::tłumaczeń
::zostalo::zostało
::dlugoterminowych::długoterminowych
::rozglądac::rozglądać
::szczegolnie::szczególnie
::potwórzenia::powtórzenia
::źródel::źródeł
::zauwazyłeś::zauważyłeś
::krokow::kroków
::zamowienie::zamówienie
::tlumaczy::tłumaczy
::zaplaty::zapłaty
::jeżdża::jeżdżą
::długośći::długości
::ćwiczyc::ćwiczyć
::zwiekszajacy::zwiększajacy
::meżczyzn::mężczyzn
::mieśni::mięśni
::byly::były
::nawiązesz::nawiążesz
::stawal::stawał
::pieniadze::pieniądze
::pamieć::pamięć
::sa::są
::upadlość::upadłość
::kończa::kończą
::sprzedazowe::sprzedażowe
::umiejętnóściami::umiejętnościami
::wracal::wracał
::podciągnąc::podciągnąć
::komorkowy::komórkowy
::ciąglych::ciągłych
::duzych::dużych
::waznego::ważnego
::waznymi::ważnymi
::skutecznosc::skuteczność
::zapisac::zapisać
::zapisac::zapisać
::jezykach::językach
::tlumaczenia::tłumaczenia
::ponosza::ponoszą
::póxniej::później
::wyłacza::wyłącza
::wyposazone::wyposażone
::zapomniec::zapomnieć
::rozważyc::rozważyć
::dzialają::działają
::dlużej::dłużej
::płacic::płacić
::jeydnie::jedynie
::trasfery::transfery
::większośc::większość
::laciny::łaciny
::waznym::ważnym
::znajomóść::znajomość
::używac::używać
::źródlowe::źródłowe
::wybierac::wybierać
::rządać::żądać
::rozbudowac::rozbudować
::antyafsda::antykataboliczne
::Zaiwera::Zawiera
::trenigów::treningów
::trenuja::trenują
::mięśnoiwej::mięśniowej
::wspomorze::wspomoże
::skutecnza::skuteczna
::nastomiast::natomiast
::wchodzilo::wchodziło
::wrecz::wręcz
::myśle::myślę
::polskę::Polskę
::uzywania::używania
::słąbszy::słabszy
::miałą::miała
::tyl::tył
::bedą::będą
::malymi::małymi
::liczyc::liczyć
::jasnośc::jasność
::grubośc::grubość
::wskazuja::wskazują
::uzytkownika::użytkownika
::sięci::sieci
::koniecznośc::konieczność
::cżesto::często
::zauwazy::zauważy
::wyczuce::wyczucie
::napisac::napisać
::wiedyz::wiedzy
::latwiejsze::łatwiejsze
::zaglądac::zaglądać
::tlumaczenie::tłumaczenie
::bardziej odporni::odporniejsi
::wyzej::wyżej
::zaangazowane::zaangażowane
::napiec::napięć
::produtków::produktów
::wzbudzal::wzbudzał
::Zwróc::Zwróć
::publicznośc::publiczność
::pisza::piszą
::dizała::działa
::sprzedazy::sprzedaży
::nawiąząć::nawiązać
::pan::Pan
::wrzuce::wrzucę 
::wysyłaja::wysyłają 
::pan::Pan
::dodac::dodać
::dziekuje::dziękuję
::pchnąc::pchnąć
::teksy::teksty
::śnieznobiałego::śnieżnobiałego
::mieśniowych::mięśniowych
::łaczy::łączy
::mieśnie::mięśnie
::zwiekszają::zwiększają
::zwiekszyć::zwiększyć
::wplywa::wpływa
::ilóść::ilość
::połącznie::połączenie
::ośób::osób
::rozpuszczalnośc::rozpuszczalność
::regenrację::regenerację
::rodzajow::rodzajów
::odzywczych::odżywczych
::poracja::porcja
::uzupełnic::uzupełnić
::wydajnosć::wydajność 
::książke::książkę
::zaangazowanie::zaangażowanie
::kóry::który
::dokładnośc::dokładność
::dokladnie::dokładnie
::nastapić::nastąpić
::dzialo::działo
::pomysłow::pomysłów
::angazujesz::angażujesz
::dziala::działa
::ilośći::ilości
::pozostawac::pozostawać
::miesiecy::miesięcy
::osiągaly::osiągały
::r1::®
::moge::mogę
::oglada::ogląda
::takze::także
::połaczyć::połączyć
::urządzen::urządzeń
::mózna::można
::usludze::usłudze
::wyglądalo::wyglądało
::zmniejszyc::zmniejszyć
::Zrównowazony::Zrównoważony
::karme::karmę
::siemie::siemię
::ilościa::ilością
::bozita::Bozita
::świeżośc::świeżość
::róznej::różnej
::miesa::mięsa
::malego::małego
::psow::psów
::służa::służą
::jedza::jedzą
::tluszczem::tłuszczem
::mięśa::mięsa
::mieso::mięso
::regulujacy::regulujący
::aktywnośc::aktywność
::świezością::świeżością
::zawartośc::zawartość
::zamykac::zamykać
::obawiac::obawiać
::kotow::kotów
::świezości::świeżości
::przechowywac::przechowywać
::Iso::ISO
::Głownym::głównym
::zgnieśc::zgnieść
::kawalki::kawałki
::malych::małych
::sklad::skład
::wolowe::wołowe
::szwecji::Szwecji
::jakóści::jakości
::zarowno::zarówno
::większóści::większości
::skłąd::skład
::dostarczająćej::dostarczającej
::nalezy::należy
::slużą::służą
::mieśa::mięsa
::wpływajacego::wpływającego
::nadwage::nadwagę
::o3::Omega-3
::o6::Omega-6
::Macrogard:: MacroGard® 
::odpornosc::odporność
::odzywcze::odżywcze
::cierpiacych::cierpiących
::Najwazniejszymi::Najważniejszymi
::wyjatkowo::wyjątkowo
::pracujacych::pracujących 
::jakósci::jakości
::wywoływac::wywoływać
::chronia::chronią
::sa::są
::własciwości::właściwości
::psób::psów
::przechodza::przechodzą
::prawidlowego::prawidłowego
::zawartośc::zawartość
::wywołuja::wywołują
::skłądniki::składniki
::zabraklo::zabrakło
::wlaścicieli::właścicieli
::antyoksydantow::antyoksydantów
::calym::całym
::następujace::następujące
::kilogramow::kilogramów
::takzę::także
::prolbemy::problemy
::pokarmow::pokarmów
::powyzej::powyżej
::ważacym::ważącym
::świezy::świeży
::możliwośc::możliwość
::zaanwansowanych::zaawansowanych
::umiejetności::umiejętności
::milionow::milionów
::rozwijac::rozwijać
::użyc::użyć
::uzyskac::uzyskać
::okolo::około
::opóxniona::opóźniona
::rózni::różni
::rzetony::żetony
::wsyzstko::wszystko
::rzetonów::żetonów
::pasowal::pasował
::naśladowal::naśladował
::poznałes::poznałeś
::nosza::noszą
::pasowala::pasowała
::Holdem::Hold'em
::protszym::prostszym
::oferuja::oferują
::połowe::połowę
::stworza::stworzą
::możńa::można
::spotkac::spotkać
::mozesz::możesz
::poznac::poznać
::rozwiazaniem::rozwiązaniem
::umiejętnóść::umiejętność
::slabe::słabe
::wybrac::wybrać
::trwalośc::trwałość
::wyróżniaja::wyróżniają
::powodujacych::powodujących
::wplywający::wpływający
::mieso::mięso
::uslugom::usługom
::iloscią::ilością
::sprawiac::sprawiać
::maly::mały
::większośc::większość
::równięz::również
::wymienilismy::wymieniliśmy
::widzialeś::widziałeś
::musze::muszę
::wymyślec::wymyślić
::przekonac::przekonać
::kwote::kwotę
::spólek::spółek
::karte::kartę
::wygrywac::wygrywać
::wymagaja::wymagają
::nauczyc::nauczyć
::wplacać::wpłacać
::kazdej::każdej
::mozesz::możesz 
::dotyczacej::dotyczącej
::czesto::często
::pamietać::pamiętać
::możliwośc::możliwość
::poprawiąją::poprawiają
::wartosciowe::wartościowe
::pozwalajacą::pozwalającą
::miesniowej::mięśniowej
::przyjeciu::przyjęciu
::odzywka::odżywka
::odpornosć::odporność
::problemow::problemów
::mężćzyzn::mężczyzn
::ćwiczen::ćwiczeń
::dostarczająća::dostarczajaca
::miesniową::mięśniową
::wytrzymalość::wytrzymałość
::moca::mocą
::sily::siły
::zawartosć::zawartość
::latwa::łatwa
::odzywiające::odżywiające
::najwazniejsza::najważniejsza
::budowac::budować
::zadziala::zadziala
::siłe::siłę
::cwiczenia::ćwiczenia
::ćwiczyc::ćwiczyć
::zwiekszające::zwiększające
::wydajnośc::wydajność
::popularnośc::popularność
::osiągneli::osiągnęli
::pragna::pragną
::angazowania::angażowania
::przedsiębiorczosci::przedsiębiorczości
::wynosza::wynoszą
::okolicznośći::okolicznośCi
::smartona::smartfona
::przelożyć::przełożyć
::połaczone::połączone
::wazny::ważny
::dźwiekowa::dźwiękowa
::dźwiek::dźwięk
::mogly::mogły
::dxwiękowa::dźwiękowa
::dźwieku::dźwięku
::nosic::nosić
::dźwiekowe::dźwiękowe
::dźwiekową::dźwiękową
::głosniki::głośniki
::ilośćią::ilością
::pojawiaja::pojawiają
::śróba::śruba
::szczególowe::szczegółowe
::pozbyc::pozbyć
::skorę::skórę
::uzywamy::używamy
::odpowiedx::odpowiedź
::zaangazowaniu::zaangażowaniu
::dlugo::długo
::wydrukow::wydruków
::cene::cenę
::większośc::większość
::nalezy::należy
::drukarke::drukarkę
::szybkośc::szybkość
::mobilnośc::mobilność
::sa::są
::zdjeć::zdjęć
::drukowac::drukować
::pojemnośc::pojemność
::sa::są
::możliwośc::możliwość
::skończa::skończą
::większosć::większość
::wifi::Wi-Fi
::każego::każdego
::pozwalaja::pozwalają
::przeprowadzajace::przeprowadzajace
::porozmawiac::porozmawiać
::tlumaczenie::tłumaczenie
::zostaly::zostały
::miales::miałeś
::odzywczych::odżywczych
::skóre::skórę
::zastosowac::zastosować
::poprawic::poprawić
::masazu::masażu
::opóxnienia::opóźnienia
::poźniej::później
::gre::grę
::przeziebienie::przeziębienie
::tlumacza::tłumacza
::okreslone::określone
::stalego::stałego
::tlumaczeniu::tłumaczeniu
::określic::określić
::okreslaniu::określaniu
::skorzystac::skorzystać
::uwaznie::uważnie
::zauwazymy::zauważymy
::rózne::różne
::poslugujesz::posługujesz
::podążąją::podążają
::najczęśćiej::najczęściej
::przykłąd::przykład
::żoładka::żołądka
::mieśniowe::mięśniowe
::działąnie::działanie
::nieporządanych::niepożądanych
::cięzko::ciężko
::poteżny::potężny
::załaczniku::załączniku
::wieksza::większa
::uzyłem::użyłem
::poznawac::poznawać
::porzadku::porządku
::manuka::Manuka
::zebów::zębów
::witalnośc::witalność
::wlosów::włosów
::dzialań::działań 
::jezykowym::językowym
::poprzestac::poprzestać
::zdenerować::zdenerwować
::osiągniecia::osiągnięcia
::pochodza::pochodzą
::najprotszych::najprotszych
::troche::trochę
::sprawe::sprawę
::przeciwieńśtwie::przeciwieństwie
::syzbko::szybko
::łykac::łykać
::trenujacych::trenujących
::wplywających::wpływających
::ilosc::ilość
::właściwośći::właściwości
::przecietny::przeciętny
::bieżaco::bieżąco
::ksiażek::książek
::zaskakujacym::zaskakującym
::słow::słów
::zaangażowac::zaangażować
::zaangazować::zaangażować
::treścia::treścią
::substacji::substancji
::dawac::dawać
::wskazywac::wskazywać
::powazną::poważną
::sięgnąc::sięgnąć
::trenowac::trenować
::pozytecznych::pożytecznych
::odzywcych::odżywczych
::wazniejsi::ważniejsi
::szcześćie::szczęście
::kazde::każde
::działan::działań
::dodawac::dodawać
::salatek::sałatek
::społęczeństwa::społeczeństwa
::krakowa::Krakowa
::apartamen::apartament
::otylości::otyłości
::znajduja::znajdują
::żę::że
::eksluzywne::ekskluzywne
::wychodza::wychodzą
::popelniają::popełniają
::wlasnej::własnej
::będzię::będzie
::dziekuję::dziękuję
::zabijaja::zabijają
::żoładku::żołądku
::szczęscie::szczęście
::poruszac::poruszać
::indeksowac::indeksować
::treśći::treści
::łączacym::łączącym
::sa::są
::kliknąc::kliknąć
::konkurowac::konkurować
::komentowac::komentować
::zwiekszenie::zwiększenie
::zwiekszy::zwiększy
::uchronic::uchronić
::uniknąc::uniknąć
::przechódź::przechodź
::odzywiania::odżywiania
::odzywczych::odżywczych
::skupic::skupić
::przywiazuje::przywiązuje
::większosc::większość
::mysza::myszą
::android::Android
::androidem::Androidem
::pozbyc::pozbyć
::budowe::budowę
::tanszym::tańszym
::kostke::kostkę
::zlotych::złotych
::udac::udać
::zweryfikowac::zweryfikować
::przypominac::przypominać
::wazna::ważna 
::większosci::większości
::sprzet::sprzęt
::badanai::badania
::spowoli::spowolni
::wyciszająćy::wyciszający
::kopozycję::kompozycję
::rozluźna::rozluźnia
::problami::problemami
::najprotszym::najprostszym
::niewielke::niewielkie
::nawte::nawet
::zakłądają::zakładają
::obciązeniem::obciążeniem
::cieżarach::ciężarach
::wymagajace::wymagające
::osiagnąć::osiagnąć
::osiagnąć::osiągnąć
::póxniejsze::późniejsze
::marzyleś::marzyłeś
::odmładzajace::odmładzające
::niepożadane::niepożądane
::pamieci::pamięci
::stawyw::statyw
::cięzkiego::ciężkiego
::obciązenia::obciążenia
::stawywu::statywu
::kosztuja::kosztują
::odłożyc::odłożyć
::możliwośc::możliwość
::srodkiem::środkiem
::wydajnośći::wydajności
::Ssd::SSD
::wymagajacych::wymagających
::mięsniowego::mięśniowego
::osiagnąc::osiągnąć
::osiagnać::osiągnąć
::działą::działa
::dotykac::dotykać
::wspólpracować::współpracować
::czlowiek::człowiek
::przyciagniemy::przyciągniemy
::pozytecznie::pożytecznie
::łątwych::łatwych
::łątwiej::łatwiej
::wartosci::wartości
::chorobe::chorobę
::cieżarami::ciężarami
::szukajace::szukające
::rózne::różne
::spodziewac::spodziewać
::swietnym::świetnym
::gb::GB
::wyposazono::wyposażono
::głosników::głośników
::wygrac::wygrać
::czytac::czytać
::widziałes::widziałeś
::ręke::rękę
::wyeliminowac::wyeliminować
::uzywając::używając
::podjąc::podjąć
::świete::święte
::wspomoga::wspomogą
::wykonywac::wykonywać
::osiagamy::osiągamy
::zapominac::zapominać
::cięzar::ciężar
::zapisywac::zapisywać
::ulegac::ulegać
::pamietac::pamiętać
::powodowac::powodować
::uniknać::uniknąć
::wytrzymałośc::wytrzymałość
::pewnosć::pewność
::przekładac::przekładać
::podgrzac::podgrzać
::wypóbuj::wypróbuj
::podnosic::podnosić
::zwiekszyć::zwiększyć
::mozesz::możesz
::połaczony::połączony
::zaangazowaniem::zaangażowaniem
::wpływac::wpływać
::wpłynąc::wpłynąć
::kosci::kości
::powiazane::powiązane
::poteżnym::potężnym
::ksiażkę::książkę
::błedów::błędów
::cześciej::częściej
::bład::błąd
::niecheć::niechęć
::róznice::różnice
::widac::widać
::rzadkościa::rzadkością
::sprawic::sprawić
::źródłeł::źródeł
::zauważyc::zauważyć
::stac::stać
::przepisywac::przepisywać
::zwizualizowac::zwizualizować
::jestesmy::jesteśmy
::przewidywac::przewidywać
::podświadomośc::podświadomość
::wynikajace::wynikające
::negocjowac::negocjować
::własnie::właśnie
::umiejętnosć::umiejętność
::okresloną::określoną
::ogladając::oglądająć
::opracowal::opracował
::zaangazowanych::zaangażowanych
::ukrywac::ukrywać
::wyjasniła::wyjaśniła
::koncetrować::koncentrować
::robie::robię
::pozostac::pozostać
::decyzyjnośc::decyzyjność
::odpowiedzialnośc::odpowiedzialność
::osiągneliśmy::osiągnęliśmy
::ilośc::ilość
::przejsć::przejść
::menagerami::managerami
::biora::biorą
::narzekac::narzekać
::zapobiegac::zapobiegać
::odzywczymi::odżywczymi
::żywnosć::żywność
::wlaśnie::właśnie
::poglad::pogląd
::takze::także
::pojawiac::pojawiać
::pokazaly::pokazały
::przerazony::przerażony
::glowie::glowie
::wpadac::wpadać
::dopasowac::dopasować
::osiagnąć::osiągnąć
::kolejncyh::kolejnych
::kamila::Kamila
::kamili::Kamili
::monika::Monika
::pokonac::pokonać
::mowi::mówi
::złozył::złożył
::łamliwośc::łamliwość
::krwioobiegu::krwiobiegu
::wchłanialnośc::wchłanialność
::możę::może
::pracowalem::pracowałem
::krwionosnych::krwionośnych
::ogrod::ogród
::niemiec::Niemiec
::żoładkiem::żołądkiem
::większośc::większość
::dlugi::długi
::, jak::  jak
::uzywać::używać
::skutecznośc::skuteczność
::obniżyc::obniżyć
::odzywiałem::odżywiałem
::uprawiac::uprawiać
::temu, nie::temu nie
::cieżar::ciężar
::temu, uzupełnisz::temu uzupełnisz
::cwiczenie::ćwiczenie
::niej, możesz::niej możesz
::niej, rozwijamy::niej rozwijamy
::cwiczeń::ćwiczeń
::mięsnie::mięśnie
::slady::ślady
::mięsnie::mięśnie
::wydajnosci::wydajności
::rzęźbę::rzeźbę
::będa::będą
::, pozwala:: pozwala
::póxnym::późnym
::, niż:: niż
::głownych::głównych
::odpornośc::odporność
::działan::działań
::marnuja::marnują
::powaznym::poważnym
::lekcewarzyć::lekceważyć
::pracowac::pracować
::bardizej::bardziej
::denerwowac::denerwować
::powinienes::powinieneś
::zmus::zmuś
::niewlaściwe::niewłaściwe
::przyjrzec::przyjrzeć
::żoładka::żołądka
::rodzielczośc::rozdzielczość
::pobrałes::pobrałeś
::eksperymentowac::eksperymentować
::dostosowac::dostosować
::edytowac::edytować
::połacznie::połączenie
::nowośc::nowość
::skupily::skupiły
::właściwóści::właściwości
::badan::badań
::, niż:: niż
::meżczyznach::mężczyznach
::intensywnośc::intensywność
::połaczeniem::połączeniem
::rosliną::rośliną
::właściwosciami::właściwościami
::ryzykowac::ryzykować
::smazony::smażony
::podrózy::podróży
::odzywiać::odżywiać
::wode::wodę
::ilośc::ilość
::wytrzymałośc::wytrzymałość
::tluszczu::tłuszczu
::przyswalajną::przyswajalną
::sa::są
::spozywamy::spożywamy
::powazne::poważne
::póxniejszym::późniejszym
::jesli::jeśli
::opowiadac::opowiadać godzinami
::pisac::pisać
::przełozyć::przełożyć
::nalezy::należy
::pryzkład::przykład
::okreslić::określić
::wyizolowac::wyizolować
::porównac::porównać
::narazeni::narażeni
::odzywienie::odżywienie
::ocieżały::ociężały
::dojsć::dojść
::cwiczysz::ćwiczysz
::hleb::chleb
::stymulowac::stymulować
::synteze::syntezę
::długotrwalego::długotrwałego
::przynosza::przynoszą
::posilków::posiłków
::musza::muszą
::dolegliwośc::dolegliwość
::płodnośc::płodność
::preparatow::preparatów
::przywrócic::przywrócić
::wzmocnic::wzmocnić
::liśc::liść
::masci::maści
::rosliny::rośliny
::uzywane::używane
::Brazyli::Brazylii
::skorzytać::skorzystać
::plemie::plemię
::posłuzyć::posłużyć
::postepuje::postępuje
::slodki::słodki
::większośc::większość
::srodków::środków
::odnosnie::odnośnie
::opierac::opierać
::przykłądowo::przykładowo
::odzywianiem::odżywianiem
::zabrac::zabrać
::wrazliwa::wrażliwa
::pieknym::pięknym
::dźwieków::dźwięków
::patrzec::patrzeć
::podlogi::podłogi
::doroslych::dorosłych
::najmlodszych::najmłodszych
::bawia::bawią
::krwionosny::krwionośny
::podawac::podawać
::cierpliwośc::cierpliwość
::tkanke::tkankę
::dluga::długa
::zamknęly::zamknęły
::stosowac::stosować
::większosc::większość
::dbala::dbała
::mialy::miały
::rosji::Rosji
::przyrode::przyrodę
::powstal::powstał
::niechęc::niechęć
::zostaly::zostały
::zaczęla::zaczęła
::kadluba::kadłuba
::wykorzystywac::wykorzystywać
::niemców::Niemców
::pilotarzu::pilotażu
::pilotarzem::pilotażem
::zachowal::zachował
::wzgłędu::względu
::zwrotnośc::zwrotność
::walke::walkę
::soji::soi
::póxnych::późnych
::przekasek::przekąsek
::poprawic::poprawić
::bialka::białka 
::masujaca::masująca
::spróbowac::spróbować
::narazone::narażone
::złacz::złącz
::głosnika::głośnika
::lodówke::lodówkę
::prad::prąd
::urzadzeń::urządzeń
::opóxnić::opóźnić
::wysokośc::wysokość
::poszukac::poszukać
::okreslonym::określonym
::uzywanie::używanie
::pozwalajace::pozwalajace
::częśćiach::częściach
::Panstwa::Państwa
::dosc::dość
::wykopywac::wykopywać
::slonecznym::słonecznym
::pieknie::pięknie
::zalezności::zależności
::ciesza::cieszą
::sa::są 
::piekne::piękne
::pieknego::pięknego
::głębokośc::głębokość
::holera::cholera
::wypytac::wypytać
::kleint::klient
::daltego::dlatego
::udzielajacych::udzielających\
::zwrocić::zwrócić
::uratowac::uratować
::umowe::umowę
::gdzies::gdzieś
::mogł::mógł
::zaległośc::zaległość
::sprzetu::sprzętu
::soba::sobą
::przyjmowac::przyjmować
::zwiększyc::zwiększyć
::suplementow::suplementów
::myslą::myślą
::wydobyc::wydobyć
::odbudowywac::odbudowywać
::VITARGO::VITARGO®
::dłuzsze::dłuższe
::konopii::konopi
::dziure::dziurę
::skoncetrowanych::skoncentrowanych
::uwazam::uważam
::uwazam::uważam
::wyrózni::wyróżni
::rozdzielczosci::rozdzielczości
::dziela::dzielą
::podrózują::podróżują
::Hdd::HDD
::glośników::głośników
::sluchania::słuchania
::malym::małym
::cieżarowych::cęeżarowych
::ukłąd::układ
::zdobywac::zdobywać
::alergi::alergii
::parti::partii
::wspołpracują::współpracują
::takżę::także
::nauczylismy::nauczyliśmy
::wiekszośc::większość
::spożywac::spożywać
::cięzarem::ciężarem
::kursantow::kursantów
::korzysci::korzyści
::dostep::dostęp
::odbierac::odbierać
::krażęnie::krążenie
::cięzkich::ciężkich
::skórcze::skurcze
::zwiekszona::zwiększona
::obrzeków::obrzęków
::najwazniejsze::najważniejsze
::elastycznośc::elastyczność
::gardlo::gardło
::poprawe::poprawę
::dolegliwośći::dolegliwośCi
::desing::design
::śledzic::śledzić
::zwieksz::zwiększ
::dolarow::dolarów
::będa::będą
::porządaną::pożądaną
::zamowień::zamówień
::ksiażki::książki
::usiadź::usiądź
::osiągnać::osiągnąć
::iż::że
::najwazniejsze::najważniejsze
::bialko::białko
::nieprawidlowe::nieprawidłowe
::hamują anabolizm::hamują katabolizm
::odzywiasz::odżywiasz
::bialek::białek
::przygladając::przyglądając
::efektywnośc::efektywność
::zajrzec::zajrzeć
::the lunch::lunch
::the breakfast::breakfast
::the home::home
::osiagniesz::osiągniesz
::porzucic::porzucić
::świadomośc::świadomość
::chcialalby::chcialałaby
::tasmowej::taśmowej
::kóra::kura
::ciezar::ciężar
::powloki::powłoki
::powloką::powłoka
::widocznośc::widoczność
::pieknego::pięknego
::jakośc::jakość
::wyposazenia::wyposażenia
::niektorych::niektórych
::nieruchomosci::nieruchomości
::nieruchomośc::nieruchomość
::osiągnac::osiągnąć
::wyciągnąc::wyciągnąć
::zacząc::zacząć
::korzysci::korzyści
::zamknąc::zamknąć
::rózny::różny
::własnie::właśnie
::szczęscia::szczęścia
::radosć::radość
::powstrzymac::powstrzymać
::ując::ująć
::tluszcz::tłuszcz
::przeciwslonecznych::przeciwsłonecznych
::zacząłes::zacząłeś
::cisnienie::ciśnienie
::wejśc::wejść
::rozmowca::rozmówca
::miłośc::miłość
::drązku::drążku
::elementow::elementów
::odwlekac::odwlekać
::patrza::patrzą
::poczuc::poczuć
::cieżarów::ciężarów
::kilkanascie::kilkanaście
::zwiekszać::zwiększać
::wyjasnienie::wyjaśnienie
::chodząć::chodząc
::siedząć::siedząc
::ograniczen::ograniczeń
::obciążęniu::obciążeniu
::dzialać::działać
::otyłośc::otyłość
::opóxnienie::opóźnienie
::zalecen::zaleceń
::zwiekszenie::zwiększenie
::rozjasnić::rozjaśnić
::zdolnośc::zdolność
::otyłośc::otyłość
::zajmujace::zajmujące
::podpiąc::podpiąć
::podłaczenie::podłączenie
::głośnomowiącego::głośnomówiącego
::przeciwsloneczna::przeciwsłoneczna
::głośnomowiących::głośnomówiących
::odchudzająće::odchudzające
::schudnac::schudnąć
::schudnać::schudnąć
::przyjąc::przyjąć
::dukana::Dukana
::dukana::Dukana
::montignaca::Montignaca
::obliczyc::obliczyć
::dzieki::dzięki
::szczegolną::szczególną
::połaczymy::połączymy
::skłonnośc::skłonność
::tydzien::tydzień
::zwiekszający::zwiększający
::funkjocnowania::funkcjonowania
::zwiekszania::zwiększania
::usunąc::usunąć
::dostarczyc::dostarczyć
::kalorycznośc::kaloryczność
::utrzymywac::utrzymywać
::dobrac::dobrać
::wazniejszego::ważniejszego
::zwiazanych::związanych
::lublinie::Lublinie
::uzupelnić::uzupełnić
::plytek::płytek
::niiezaplacone::niezapłacone
::przyszłośc::przyszłość
::małzonków::małżonków
::skończyc::skończyć
::póxniejszej::późniejszej
::teksu::tekstu
::sprzedazowego::sprzedażowego
::róznymi::różnymi
::wplywającym::wpływającym
::umiejętnośc::umiejętność
::zapamietają::zapamiętają
::zółtej::żółtej
::mowisz::mówisz
::działałes::działałeś
::angazuje::angażuje
::ilośc::ilość
::obciażeniem::obciążeniem
::zauwazyleś::zauważyłeś
::zmieniac::zmieniać
::zamontowac::zamontować
::wydłużyc::wydłużyć
::tylem::tyłem
::informuja::informują
::polegac::polegać
::imadlowym::imadłowym
::przekłamywac::przekłamywać
::podrózuje::podróżuje
::częsciom::częściom
::skutecznosci::skuteczności
::róznorodnych::różnorodnych
::trzymac::trzymać
::wieksza::większa
::pomożę::pomoże
::przeziebienia::przeziębienia
::maśc::maść
::cieżkich::ciężkich
::srodek::środek
::nałożyc::nałożyć
::placić::płacić
::gardla::gardła
::sluz::śluz
::ciagu::ciągu
::sluzu::śluzu
::stawow::stawów
::rozluxnienie::rozluźnienie
::przeszlością::przeszłością
::połozyć::położyć
::zadziala::zadziała
::konska::końska
::konsytencja::konsystencja
::oznaczajace::oznaczające
::mięsniowe::mięśniowe
::kojarza::kojarzą
::uczuc::uczuć
::szałwi::szałwii
::dziaseł::dziąseł
::nawilżajace::nawilżające
::czlowieka::człowieka
::narazonych::narażonych
::częstotliwośc::częstotliwość
::tansze::tańsze
::zdecydowac::zdecydować
::słuzyć::służyć
::elektrostatycznośc::elektrostatyczność
::pozwolic::pozwolić
::róznicę::różnicę
::powazna::poważna
::doplaca::dopłaca
::doplata::dopłata
::częsciowa::częściowa
::żoładek::żołądek
::kandydowac::kandydować
::pomozemy::pomożemy
::tluszczy::tłuszczy
::energetyzujace::energetyzujące
::slabsze::słabsze
::powaznych::poważnych
::większośc::większość
::kropelke::kropelkę
;2308
::ludxmi::ludźmi
::ciala::ciała
::zoładek::żołądek
::wchlanianie::wchłanianie
::nieprawidlowa::nieprawidłowa
::wlaściwości::właściwości
::enzymow::enzymów
::zjeśc::zjeść
::ilosci::ilości
::stsoowania::stosowania
::gramow::gramów
::glodu::głodu
::odchudzajacych::odchudzających
::tanca::tańca
::przejśc::przejść
::zaczynąją::zaczynają
::przyjśc::przyjść
::stracic::stracić
::bialkową::białkową
::obciązenie::obciążenie
::połaczenie::połączenie
::masla::masła
::pięc::pięć
::zmniejza::zmniejsza
::antyoskydantem::antyoksydantem
::koścmi::kośćmi
::ogladać::oglądać
::objadac::objadać
::uchronic::uchronić
::komorki::komórki
::odpowiadaja::odpowiadają
::przypisywac::przypisywać
::tloczonych::tłoczonych
::uzupelniać::uzupełniać
::jakiegos::jakiegoś
::makijarzu::makijażu
::groxny::groźny
::nadcisnienie::nadciśnienie
::ćwiczenie::ćwiczenie
::poczatkujące::początkujące
::zdroiwe::zdrowie
::trafiaja::trafiają
::utrzymac::utrzymać
::zupelnie::zupełnie
::duzym::dużym
::społecznosci::społeczności
::wspólpraca::współpraca
::lamba::lambda
::moze::może
::jeset::jest
::nalezy::należy
::bezpieczenstwo::bezpieczeństwo
::głębokośc::głębokość
::cisnienia::ciśnienia
::światel::świateł
::bezpieczeńtwa::bezpieczeństwa
::najwazniejsze::najważniejsze
::produków::produktów
::świezym::świeżym
::daja::dają
::zaczęly::zaczęły
::nałozenie::nałożenie
::odzywianie::odżywianie
::produktow::produktów
::nieprawidlowego::nieprawidłowego
::prawidlową::prawidłową
::nieprawidlowy::nieprawidłowy
::fitnesu::fitnessu
::cierpliwosci::cierpliwości
::doplywa::dopływa
::moze::może
::kamuflarzu::kamuflażu
::kamuflarz::kamuflaż
::ziola::zioła
::usunąc::usunąć
::zaprezentowac::zaprezentować
::nieprawidlową::nieprawidłową
::moze::może
::wystepuje::występuje
::mięsnie::mięśnie
::prawidlowe::prawidłowe
::zwiekszaniem::zwiększaniem
::dzialania::działania
::uprawiaja::uprawiają
::mozgu::mózgu
::glowie::głowie
::prawidlowy::prawidłowy
::planowac::planować
::rozciąniesz::rozciągniesz
::czulem::czułem
::wątpliwosci::wątpliwości
::mówiac::mówiąc
::angazować::angażować
::męczyl::męczył
::tluszczowej::tłuszczowej
::skladników::składników
::sennośc::senność
::siedzialeś::siedziałeś
::trzymaja::trzymają
::najwiekszy::największy
::rozwiazanie::rozwiązanie
::umiejętnośći::umiejętności
::znajomośc::znajomość
::watroba::wątroba
::zwięrząt::zwierzą
::zawartościa::zawartością
::produkujaca::produkująca
::wytrzymałośc::wytrzymałość
::środkow::środków
::odzywek::odżywek
::doswiadczonym::doświadczonym
::jakośią::jakością
::jka::jak
::wspomagająće::wspomagające
::piora::pióra
::dojśc::dojść
::śróby::śruby
::śróbami::śrubami
::śróbę::śrubę
::końcowek::końcówek
::faze::fazę
::osiągnięmy::osiągniemy
::jeśc::jeść
::slodzik::słodzik
::przemyslany::przemyślany
::stanąc::stanąć
::skakac::skakać
::uksztaltować::ukształtować
::zaanwansowania::zaawansowania
::ciąglym::ciągłym
::osiądających::osiadających
::wnetrzu::wnętrzu
::sprawdx::sprawdź
::bardz::bardzo
::oglądac::oglądać
::dokanalowy::dokanałowy
::trwałośc::trwałość
::godizn::godzin
::głosno::głośno
::prędkosci::prędkości
::wierzach::wieżach
::zapamietywanie::zapamiętywanie
::wiezy::wieży
::głowe::głowę
::powiedziec::powiedzieć
;; tukej
::wczesnie::wcześnie
::produktow::produktów
::srodowisko::środowisko
::zastosownaia::zastosowania
::trwala::trwała
::permamentnego::permanentnego
::poświęcic::poświęcić
::zablokowac::zablokować
::poświęcic::poświęcić
::odwiedzajace::odwiedzające
::srodki::środki
::watrobę::wątrobę
::wytrzymalościowe::wytrzymałościowe
::dodałes::dodałeś
::uciązliwe::uciążliwe
::srodowisku::środowisku
::zwiekszone::zwiększone
::krwionosne::krwionośne
::tlumaczem::tłumaczem
::zamkniete::zamknięte
::musialeś::musiałeś
::właczyć::włączyć
::słuzy::służy
::Uzywając::Używając
::powiększyc::powiększyć
::wyposazonego::wyposażonego
::sprawdzaja::sprawdzają
::osiągniecie::osiągnięcie
::uwazny::uważny
::podrózujesz::podróżujesz
::przeznaczyc::przeznaczyć
::uzytkowania::użytkowania
::zlodziej::złodziej
::słuzyly::służyły
::deskorolke::deskorolkę
::uniewersalne::uniwersalne
::Zwroć::zwróć
::jesli::jeśli
::poradzic::poradzić
::usuwac::usuwać
::zniechęcac::zniechęcać
::zmywarke::zmywarkę
::programow::programów
::zmywarke::zmywarkę
::mieszcza::mieszczą
::głosnymi::głośnymi
::kierowac::kierować
::wytrzymaly::wytrzymały
::pożadanego::pożądanego
::rozsypac::rozsypać
::wspominalismy::wspominaliśmy
::póxne::późne
::kośći::kości
::komorek::komórek
::włączyc::włączyć
::watrobie::wątrobie
::ziolowych::ziołowych
::nalezy::należy
::pojedyńczych::pojedynczych
::pojedyńczych::pojedynczych
::ziolo::zioło
::pacjentow::pacjentów
::ejst::jest
::źródlem::źródłem
::kupic::kupić
::odzywczy::odżywczy
::gęstośc::gęstość
::odróznianie::odróżnianie
::lenth::length
::przycyzny::przyczyny
::wybierajac::wybierając
::ph::pH
::cieżej::ciężej
::całosci::całości
::łątwe::łatwe
::nawadniajace::nawadniające
::ściągająće::ściągające
::kapiele::kąpiele
::przekłąda::przekłada
::powiekszającą::powiększającą
::bezuzyteczne::bezużyteczne
::wodoszczelnośc::wodoszczelność
::rzeczywistosci::rzeczywistości
::dziedzine::dziedzinę
::doswiadczenie::doświadczenie
::miałą::miała
::powloka::powłoka
::łątwo::łatwo
::zabezpieczac::zabezpieczać
::zwiazki::związki
::działanai::działania
::podjać::podjąć
::słyszałes::słyszałeś
::wlewac::wlewać
::goracej::gorącej
::jasniejsze::jaśniejsze
::cieżką::ciężką
::niepotwarzalnym::niepowtarzalnym
::odczytac::odczytać
::wartośćiowym::wartościowym
::niekorzyśc::niekorzyść
::nawilzenie::nawilżenie
::radośc::radość
::istnieja::istnieją
::kazda::każda
::pewnościa::pewnością
::będizemy::będziemy
::dzialaniu::działaniu
::polowac::polować
::znajduja::znajdują
::wyróznia::wyróżnia
::zastapiony::zastąpiony
::jakośći::jakości
::mieśći::mieści
::zasadowośc::zasadowość
::wodoodpornośc::wodoodporność
::funtion::function
::skonsultowac::skonsultować
::róznić::różnić
::prędkosć::prędkość
::spowodowac::spowodować
::plazy::plaży
::składaja::składają
::tresci::treści
::zasiegu::zasięgu
::zastanowic::zastanowić
::odbiorcow::odbiorców
::reklamowac::reklamować
::sluchu::słuchu
::kupilem::kupiłem
::potrzebowal::potrzebował
::wygladem::wyglądem
::odbieraja::odbierają
::kreatywnośc::kreatywność
::Kreatywnośc::Kreatywność
::rekę::rękę
::ogladac::oglądać
::dosć::dość
::ulątwi::ułatwi
::czcionke::czcionkę
::slowa::słowa
::wybieralem::wybierałem
::musialem::musiałem
::watroby::wątroby
::narazone::narażone
::żywnośći::żywności
::zwyklych::zwykłyhc
::społecznosciowym::społecznościowym
::stopien::stopień
::wynikac::wynikać
::będa::będą
::kumuluja::kumulują
::schowac::schować
::kupowac::kupować
::Bezsennośc::Bezsenność
::miałes::miałeś
::ciązy::ciąży
::postawic::postawić
::smierć::śmierć
::brzmiec::brzmieć
::wykorzystac::wykorzystać
::czesto::często
::odróżnic::odróżnić
::przedsiebiorcy::przedsiębiorcy
::okreslenie::określenie
::doraxnie::doraźnie
::mąke::mąkę
::estrogenow::estrogenów
::ustabilizowac::ustabilizować
::unormowac::unormować
::Dzięki nim, można::Dzięki nim, można
::stanow::stanów
::pomidorow::pomidorów
::złozone::złożone
::weglowodany::węglowodany
::rzucia::żucia
::odzywiamy::odżywiamy
::odzywia::odżywia
::owocow::owoców
::wysokosci::wysokości
::interesujace::interesujące
::pobudzajacego::pobudzającego
::stosujac::stosując
::trendow::trendów
::roslinnego::roślinnego
::głosności::głośności
::dźwiekow::dźwieków
::midi::MIDI
::dópa::dupa
::jakosc::jakość
::kontaktowac::kontaktować
::przenosne::przenośne
::wirusow::wirusów
::funkcjonalnosci::funkcjonalności
::wyposazonych::wyposażonych
::smartfonow::smartfonów
::bolem::bólem
::uzytkowniczek::użytkowniczek
::cierpien::cierpień
::wiekszość::większość
::wybor::wybór
::widht::width
::planetanych::planetarnych
::dlugość::długość
::uzywanego::używanego
::ktorymi::którymi
::ułozone::ułożone
::domow::domów
::odleglości::odległości
::bezworkowe::bezworkowe
::narazony::narażony
::sprzetem::sprzętem
::mysleć::myśleć
::zwiekszenia::zwiększenia
::otrzymuja::otrzymują
::schudla::schudła
::slowa::słowa
::głebokich::głębokich
::dlugotrwałe::długotrwałe
::miłosników::miłośników
::obliczen::obliczeń
::rekawic::rękawic
::trenuja::trenują
::bol::ból
::zwiekszeniu::zwiększeniu
::obrzeki::obrzęki
::wydłuzone::wydłużone
::skladniki::składniki
::poprawiajace::poprawiające
::tasmy::taśmy
::slużyło::służyło
::plec::płeć
::ciaży::ciąży
::narzadów::narządów
::niedoczynnośc::niedoczynność
::krawienia::krwawienia
::toczen::toczeń
::popkorn::popcorn
::popkornu::popcornu
::blonnik::błonnik
::Karol::Karol to głupek
::skrócic::skrócić
::oplaty::opłaty
::równolegly::równoległy
::portugalii::Portugalii
::lekcewazeniem::lekceważeniem
::szkołe::szkołę
::wyzszym::wyższym
::ważnosci::ważności
::zameldowac::zameldować
::niewazna::nieważna
::niepelnosprawności::niepełnosprawności
::wartosciom::wartościom
::unikac::unikać
::pradu::prądu
::połozeniu::położeniu
::wezwac::wezwać
::ukrainie::Ukrainie
::kontynuowac::kontynuować
::uniwersystety::uniwersytety
::pamiętac::pamiętać
::zwiazane::związane
::wiezienia::więzienia
::spółke::spółkę
::uzalezniony::uzależniony
::szwecji::Szwecji
::finlandii::Finlandia
::tożsamośc::tożsamość
::szecja::Szwecji
::szecji::Szwecji
::przetlumaczenie::przetłumaczenie
::narzadach::narządach
::nabial::nabiał
::postepowaniem::postępowaniem
::pełnosci::pełności
::spowodowac::spowodować
::wisni::wiśni
::wspierac::wspierać
::zawartosci::zawartości
::blonnika::błonnika
::trwaja::trwają
::zasnąc::zasnąć
::miare::miarę
::uczyc::uczyć
::posmarowac::posmarować
::maleńskiej::maleńkiej