#NoEnv
#SingleInstance force
; send the corrected word on reload (will replace the selected word)

if(%0% > 1)
    Send, %2%
; a tiny GUI setup
Gui, Add, Edit, vfrom w200  ,%Hotstring%::
Gui, Add, Edit, vto  w200 ym0,%Hotstring%
Gui, Add, Button, Default, OK
#H::
	AutoTrim Off  
	ClipboardOld = %ClipboardAll%
	Clipboard =  
	Send ^c
	ClipWait 3
	if ErrorLevel  
		return
	StringReplace, Hotstring, Clipboard, ``, ````, All  
	StringReplace, Hotstring, Hotstring, `r`n, ``r, All
	StringReplace, Hotstring, Hotstring, `n, ``r, All
	StringReplace, Hotstring, Hotstring, %A_Tab%, ``t, All
	StringReplace, Hotstring, Hotstring, `;, ```;, All
	
	; trim the word (better imo)
	Hotstring :=  Trim(Hotstring)
	
	Clipboard = %ClipboardOld% 
	
	; setting the hotstrings in the GUI
	GuiControl,, to, %Hotstring%
	GuiControl,, from, %Hotstring%::
	
	; focus to the "to" gui
	GuiControl, Focus, to
	Gui, Show
	
	; send control + a in order toselecctthe text in the "to" gui (better imo)
	Send, ^a
return

; happens when pressing the OK button
ButtonOK:

    GuiControlGet, to
    GuiControlGet, from
    Hotstring := "::" from to
    FileAppend, `n%Hotstring%, %A_ScriptFullPath%  

    ; special reload statement with the word in the "to" gui
    Run, %A_ScriptFullPath% /restart %to%

    Sleep 200
    MsgBox, 4,, The hotstring just added appears to be improperly formatted.  Would you like to open the script for editing? Note that the bad hotstring is at the bottom of the script.
    IfMsgBox, Yes, Edit
return
::doœc::doœæ
::specjalizacij::specjalizacij
::rozpoczêæie::rozpoczêcie
::spotkalem::spotka³em
::zolw::¿ó³w
::coz::có¿
::lucja::³ucja 
::wyglad::wygl¹d
::zauwazyæ::zauwa¿yæ
::znajdue::znajduje
::Lte::LTE
::LtE::LTE
::urz¹dzenei::urz¹dzenie
::zdjêæie::zdjêcie
::smarton::smartfon
::dlatego jeœli::dlatego, jeœli
::mó¿e::mo¿e
::pojawic::pojawiæ
::Sim::SIM
::rodzielczoœci::rozdzielczoœci
::cyz::czy
::pamiêc::pamiêæ
::miesi¹æ::miesi¹c
::sprobowa³a::spróbowa³a
::zydów::¿ydów
::tzry::trzy
::opróæz::oprócz
::ró¿nia::ró¿ni¹
::resturacji::restauracji
::tob¹::Tob¹
::wspó³pracow¹æ::wspó³pracowaæ
::twój::Twój
::ty::Ty
::jeœi::jeœli
::mo¿liwosci::mo¿liwoœci
::sie::siê
::t³umaczneie::t³umaczenie
::nei::nie
::lekcewarzenie::lekcewa¿enie
::ta¿ê::tak¿e 
::pamietaj::pamiêtaj
::obs³ugiwac::obs³ugiwaæ
::bêda::bêd¹
::dotyczyc::dotyczyæ
::korzytsa::korzysta
::t³umaczneia::t³umaczenia
::wiêkszoœc::wiêkszoœæ
::ise::siê
::ktorzy::którzy
::mozesz::mo¿esz
::sa::s¹
::tlumacza::t³umacza
::korzyœæi::korzyœci
::tekstow::tekstów
::strone::stronê
::teksów::tekstów
::jednie::jedynie
::obrazkow::obrazków
::utrudniaja::utrudniaj¹
::cat::CAT
::Cat::CAT
::cAT::CAT
::uwage::uwagê
::konsekwetny::konsekwentny
::¿ê::¿e
::mozna::mo¿na
::uslug::us³ug
::myœlec::myœleæ
::moga::mog¹
::wyglada::wygl¹da
::klientow::klientów
::ucza::ucz¹
::tlumaczenia::t³umaczenia
::wiadomoœæi::wiadomoœci
::tlumaczeniowych::t³umaczeniowych
::korzyœc::korzyœæ
::na prawdê::naprawdê
::b³edu::b³êdu
::jesli::jeœli
::komunikowac::komunikowaæ
::t³umaczen::t³umaczeñ
::powstaly::powsta³y
::transkrybcji::transkrypcji
::us³uge::us³ugê
::powyzszych::powy¿szych
::nalezy::nale¿y
::Jpg::JPG
::mozê::mo¿e
::ksi¹zki::ksi¹¿ki
::zycie::¿ycie
::zaangazowania::zaanga¿owania 
::m¿na::mo¿na
::zrobic::zrobiæ
::angazowany::anga¿owany
::przykladowo::przyk³adowo
::iloœc::iloœæ
::zaangazowany::zaanga¿owany
::obsluga::obs³uga
::musza::musz¹
::wieksz¹::wiêksz¹
::wspó³pracuja::wspó³pracuj¹
::mo¿liwoœc::mo¿liwoœæ
::najwiekszych::najwiêkszych
::Crm::CRM
::ktory::który
::polegaja::polegaj¹
::szczerze mówi¹c::@@
::DtP::DTP
::zajmuja::zajmuj¹
::zamowiæ::zamówiæ
::treœc::treœæ
::isê::siê
::pomoga::pomog¹
::zaoferowac::zaoferowaæ
::któe::które
::fikusnych::fikuœnych
::korzystac::korzystaæ
::czionka::czcionka
::Pdf::PDF
::styli::stylów
::zalezy::zale¿y
::podejmowac::podejmowaæ
::oddac::oddaæ
::mó¿na::mo¿na
::przetlumaczyæ::przet³umaczyæ
::umiejêtnoœc::umiejêtnoœæ
::moga::mog¹
::zlecen::zleceñ
::powinienes::powinieneœ
::nauke::naukê
::dotyczace::dotycz¹ce
::pytac::pytaæ
::umiejêtnosci::umiejêtnoœci
::jezykowe::jêzykowe
::szybcije::szybciej
::w³aœciwosci::w³aœciwoœci
::wchodza::wchodz¹
::mase::masê
::odchudzaja::odchudzaj¹
::zwieksza::zwiêksza
::mase::masê
::mieœni::miêœni
::wydawac::wydawaæ
::przyjmowac::przyjmowaæ
::dokladne::dok³adne
::po³aczenie::po³¹czenie
::miêsnie::miêœnie
::miesnie::miêœnie
::rozwin¹c::rozwin¹æ
::zwiekszenie::zwiêkszenie
::olim::olimp
::mieœniow¹::miêœniow¹
::znacznei::znacznie
::tk¿e::tak¿e
::dzêki::dziêki
::Ÿródlo::Ÿród³o
::wspomoze::wspomo¿e
::tak¿ê::tak¿e
::mieœniach::miêœniach
::ukladu::uk³adu
::az::a¿
::wydolnoœc::wydolnoœæ
::przyswalajnej::przyswajalnej
::napojow::napojów
::pojemnosci::pojemnoœci
::mieœni::miêœni
::duze::du¿e
::kóre::które
::kofeine::kofeinê
::odzywki::od¿ywki
::takze::tak¿e
::ktore::które
::¿ywnoœc::¿ywnoœæ
::nalezy::nale¿y
::zakwaszenei::zakwaszenie
::buduja::buduj¹
::bêdize::bêdzie
::zacza³::zacz¹³
::pomoze::pomo¿e
::zacz¹l::zacz¹³
::przycyznia::przyczynia
::nieporz¹danymi::niepo¿¹danymi
::nia::ni¹
::dolegliwosci::dolegliwoœci
::bedize::bêdzie
::odziezy::odzie¿y
::dzialanie::dzia³anie
::niebezpieczenstwie::niebezpieczeñstwie
::niepo¿adanych::niepo¿¹danych
::mêzczyzn::mê¿czyzn
::ukladem::uk³adem
::kazdego::ka¿dego
::zapytac::zapytaæ
::duzo::du¿o
::umowiæ::umówiæ
::bede::bêdê
::mógl::móg³
::zapoznal::zapozna³
::zmniejszyla::zmniejszy³a
::powierdza::potwierdza
::któa::która
::przeszla::przesz³a
::odzywiaj¹::od¿ywiaj¹
::zmienilo::zmieni³o
::zycia::¿ycia
::mê¿æzyzna::mê¿czyzna
::szkodza::szkodz¹
::wazy³::wa¿y³
::jednoczesnie::jednoczeœnie
::leczenei::leczenie
::poznala::pozna³a
::przeczytac::przeczytaæ
::a nad to::a nadto
::a nó¿::a nu¿
::a pro po::A propos
::absorbcja::absorpcja
::absorbcji::absorpcji
::ad.::ad
::aleji::alei
::alternatywana::alternatywna
::a¿ nad to::a¿ nadto
::badz::b¹dŸ
::badŸ::b¹dŸ
::b¹dx::b¹dŸ
::bede::bêdê
::bedê::bêdê
::bedzie::bêdzie
::bedziecie::bêdziecie
::bedziemy::bêdziemy
::bedziesz::bêdziesz
::bêda::bêd¹
::biegn¹³::bieg³
::biegnêli::biegli
::biegnê³a::bieg³a
::biegnê³o::bieg³o
::bierz¹co::bie¿¹co
::bieze::bierze
::bie¿e::bierze
::biznes plan::biznesplan
::bratowi::bratu
::bro¿ka::broszka
::brut::brud
::byc::byæ
::byl::by³
::byla::by³a
::bylem::by³em
::byliscie::byliœcie
::bylismy::byliœmy
::bylo::by³o
::byly::by³y
::chart ducha::hart ducha
::chba::chyba
::ch³opcowi::ch³opcu
::ch³opowi::ch³opu
::chor::chór
::chyab::chyba
::cibie::ciebie
::cie¿arówka::ciê¿arówka
::co i ró¿::co rusz
::co nie co::co nieco
::co nie miara::co niemiara
::codzieñ::co dzieñ
::conajmniej::co najmniej
::coprawda::co prawda
::cudzys³owia::cudzys³owu
::cudzys³owiu::cudzys³owie
::czegos::czegoœ
::czesc::czêœæ
::czesta::czêsta
::czeste::czêste
::czesto::czêsto
::czesty::czêsty
::czestych::czêstych
::czetry::cztery
::czêsci::czêœci
::czêœc::czêœæ
::czyms::czymœ
::d/s::ds.
::dla czego::dlaczego
::dla tego ¿e::dlatego ¿e
::dla tego ¿eby::dlatego ¿eby
::dlatego bo::bo
::do nie dawna::do niedawna
::do niech::do nich
::do oko³a::dooko³a
::do póki::dopóki
::do póty::dopóty
::do tych czas::dotychczas
::dobzre::dobrze
::doczynienia::do czynienia
::dokumnety::dokumenty
::domniemuje::domniemywa
::domniemujesz::domniemywasz
::domniemujê::domniemywam
::dosc::doœæ
::dosiego::do siego
::dostawaj¹::dostaj¹
::dostep::dostêp
::dosyc::dosyæ
::dozowolone::dozwolone
::dró¿ba::dru¿ba
::drzem::d¿em
::drzemy::d¿emy
::du³::dó³
::duzo::du¿o
::dwa kroæ::dwakroæ
::dzialalnoœci::dzia³alnoœci
::dzia³ac::dzia³aæ
::dzieciami::dzieæmi
::dzis::dziœ
::dzisiej::dzisiaj
::dziubek::dzióbek
::dzwiek::dŸwiêk
::d¿wiêk::dŸwiêk
::ecru::écru
::ekri::écru
::fekalii::fekaliów
::gdyz::gdy¿
::gdzie nie gdzie::gdzieniegdzie
::genitalii::genitaliów
::glos::g³os
::g³ownie::g³ównie
::g³owny::g³ówny
::hab::hab.
::histori::historii
::Hong Kong::Hongkong
::huk³o::huknê³o
::iê::siê
::iloci::iloœci
::iloœc::iloœæ
::imie::imiê
::informcje::informacje
::itd::itd.
::itp::itp.
::iwem::wiem
::j.w.::jw.
::jak¹s::jak¹œ
::jakies::jakieœ
::jakis::jakiœ
::jescze::jeszcze
::jesli::jeœli
::jeszzce::jeszcze
::jezeli::je¿eli
::jezyk::jêzyk
::jezyka::jêzyka
::jezyku::jêzyku
::juz::ju¿
::k/::k.
::Ka-ce::Katow.
::kalumni::kalumnii
::kims::kimœ
::klineta::klienta
::kliniêcie::klikniêcie
::klinij::kliknij
::kocy::koców
::kogos::kogoœ
::koleji::kolei
::korzystac::korzystaæ
::kórz::kurz
::ksi¹zka::ksi¹¿ka
::ksi¹¿e::ksi¹¿ê
::ktora::która
::ktorego::którego
::ktorej::której
::ktory::który
::ktorych::których
::ktorzy::którzy
::któa::która
::któe::które
::któy::który
::lbu::lub
::leprze::lepsze
::lini::linii
::lubieæ::lubiæ
:: =³acznie::³¹cznie
::³aæ.::³ac.
::m. in.::m.in.
::m.in::m.in.
::mai³::mia³
::mase::masê
::mass-media::mass media
::ma¿ê o::marzê o
::mêzczyzna::mê¿czyzna
::mêzczyzny::mê¿czyzny
::Mê¿cyzna::Mê¿czyzna
::miec::mieæ
::miedzy::miêdzy
::miejsce zamieszania::miejsce zamieszkania
::mieœni::miêœni
::miêdzy czasie::miêdzyczasie
::miêsni::miêœni
::milosc::mi³oœæ
::mimo, i¿::mimo i¿
::mimo, ¿e::mimo ¿e
::moga::mog¹
::mog³a by::mog³aby
::moj::mój
::mowic::mówiæ
::mowiæ::mówiæ
::moze::mo¿e
::mozna::mo¿na
::moznaby::mo¿na by
::mo¿naby::mo¿na by
::móg³ by::móg³by
::musza::musz¹
::musze::muszê
::n/::n.
::na dal::nadal
::na niech::na nich
::na poziome::na poziomie
::na prawdê::naprawdê
::na przeciw::naprzeciw
::na przeciwko::naprzeciwko
::na raz::naraz
::na tych miast::natychmiast
::na w pó³::na wpó³
::na wzajem::nawzajem
::nad zwyczaj::nadzwyczaj
::nadzieji::nadziei
::najczêsciej::najczêœciej
::najwiecej::najwiêcej
::nalezy::nale¿y
::napewno::na pewno
::naprawde::naprawdê
::naprzemian::na przemian
::naprzyk³ad::na przyk³ad
::narazie::na razie
::nast::nast.
::nastepna::nastêpna
::nastepne::nastêpne
::nastepni::nastêpni
::nastepnie::nastêpnie
::nastepny::nastêpny
::nastepnych::nastêpnych
::natomist::natomiast
::nei::nie
::nie musze::nie muszê
::nie omal::nieomal
::nie opodal::nieopodal
::nieca³kiem::nie ca³kiem
::nielada::nie lada
::niema::nie ma
::niemo¿na::nie mo¿na
::nietylko::nie tylko
::niewolno::nie wolno
::niezawsze::nie zawsze
::niz::ni¿
::nmie::mnie
::nr.::nr
::o prócz::oprócz
::od niech::od nich
::odpowied¿::odpowiedŸ
::odrazu::od razu
::okres czasu::czas
::okresie czasu::czasie
::oprocz::oprócz
::organiŸmie::organizmie
::orginalny::oryginalny
::osob¹ trzecim::osobom trzecim
::oto chodzi::o to chodzi
::oto chodzi³o::o to chodzi³o
::otrzymywac::otrzymywaæ
::p.n.e::p.n.e.
::p.n.e..::p.n.e.
::p.w.::pw.
::pare::parê
::pa¿dziernik::paŸdziernik
::pa¿dziernika::paŸdziernika
::piatek::pi¹tek
::pne::p.n.e.
::po k¹tem::pod k¹tem
::po miêdzy::pomiêdzy
::po mimo::pomimo
::po nad::ponad
::po nadto::ponadto
::po pod::popod
::po porostu::po prostu
::po przez::poprzez
::po œrodku::poœrodku
::po woli::powoli
::po za::poza
::pobie¿::pobierz
::poczatku::pocz¹tku
::poczym::po czym
::pod katem::pod k¹tem
::podczas, gdy::podczas gdy
::pojecia::pojêcia
::pojecie::pojêcie
::pojedyñcza::pojedyncza
::pojedyñcze::pojedyncze
::pojedyñczego::pojedynczego
::pojedyñczej::pojedynczej
::pojedyñczy::pojedynczy
::pojedyñczych::pojedynczych
::pokarz::poka¿
::pokolei::po kolei
::pokryjomu::po kryjomu
::pokuj::pokój
::pomimo, i¿::pomimo i¿
::pomimo, ¿e::pomimo ¿e
::ponad to::ponadto
::poniewaz::poniewa¿
::poprawila::poprawi³a
::poprostu::po prostu
::porzadek::porz¹dek
::posiadaja::posiadaj¹
::posrod::poœród
::posz³em::poszed³em
::pot wp³ywem::pod wp³ywem
::pozatym::poza tym
::po¿¹dek::porz¹dek
::po¿¹dkiem::porz¹dkiem
::po¿¹dku::porz¹dku
::pó¿niej::póŸniej
::pracowal::pracowa³
::prez::przez
::prof::prof.
::prosba::proœba
::prosze::proszê
::prpopzucja::propozycja
::pryz::przy
::przecierz::przecie¿
::przed pokój::przedpokój
::przed wczoraj::przedwczoraj
::przede dniu::przededniu
::przedewszystkim::przede wszystkim
::przekonywuj¹cy:: przekonywaj¹cy
::przyja¿ñ::przyjaŸñ
::przyklad::przyk³ad
::pzrez::przez
::raz wraz::raz w raz
::r¹by::romby
::rowniez::równie¿
::rownie¿::równie¿
::rozdzielczoœc::rozdzielczoœæ
::rozdzielczoœæi::rozdzielczoœci
::rozumiê::rozumiem
::rozwoj::rozwój
::ro¿no::ro¿en
::rónie¿::równie¿
::równierz::równie¿
::równiez::równie¿
::rz¹dana::¿¹dana
::rz¹dane::¿¹dane
:: =rz¹dania::¿¹dania
::rz¹danie::¿¹danie
::rz¹dany::¿¹dany
::rzeczywiscie::rzeczywiœcie
::sa::s¹
::samochod::samochód
::samodzienie::samodzielnie
::sciœle::œciœle
::sei::siê
::sie::siê
::sierpien::sierpieñ
::sklada::sk³ada
::skladaja::sk³adaj¹
::skladaj¹::sk³adaj¹
::skladano::sk³adano
::sobiê::sobie
::sp-nia::spó³dz.
::spowrotem::z powrotem
::sprawdzila::sprawdzi³a
::stabilnoœæi::stabilnoœci
::standart::standard
::struj::strój
::styczen::styczeñ
::styli::stylów
::sytem::system
::sytemie::systemie
::sytemu::systemu
::tak na prawdê::tak naprawdê
::takze::tak¿e
::tak¿ê::tak¿e
::tam têdy::tamtêdy
::tournee::tournée
::trzcionka::czcionka
::trzy kroæ::trzykroæ
::tu dzie¿::tudzie¿
::twoj::twój
::tym czasem::tymczasem
::tysiêce::tysi¹ce
::tyœ.::tys.
::tzreba::trzeba
::umiê::umiem
::v-ce::wice
::vzêsto::czêsto
::w brew::wbrew
::w cale::wcale
::w jak sposób::w jaki sposób
::w ko³o::wko³o
::w krótce::wkrótce
::w liniê::w linie
::w miêdzy czasie::w miêdzyczasie
::w niwecz::wniwecz
::w odró¿nieniu do::w odró¿nieniu od
::w ogule::w ogóle
::w oka mgnieniu::w okamgnieniu
::w okó³::wokó³
::w p³aw::wp³aw
::w poœród::wpoœród
::w pó³ do::wpó³ do
::w przeciwieñstwie od::w przeciwieñstwie do
::w raz z::wraz z
::w skutek::wskutek
::w œród::wœród
::w tak sposób::w taki sposób
::w tedy::wtedy
::w/g::wg
::warzy::wa¿y
::wciaz::wci¹¿
::wcia¿::wci¹¿
::wedlug::wed³ug
::Wewnêtrza::Wewnêtrzna
::wg.::wg
::wg³¹b::w g³¹b
::wiec::wiêc
::wiecej::wiêcej
::wiedze::wiedzê
::wieksz¹::wiêksz¹
::wieksze::wiêksze
::wiekszego::wiêkszego
::wiekszej::wiêkszej
::wiekszosc::wiêkszoœæ
::wiekszosci::wiêkszoœci
::wiekszoœc::wiêkszoœæ
::wiekszoœci::wiêkszoœci
::wiekszoœæ::wiêkszoœæ
::wiekszy::wiêkszy
::wiekszych::wiêkszych
::wiekszym::wiêkszym
::wiekszymi::wiêkszymi
::wiele kroæ::wielekroæ
::wie¿ê w::wierzê w
::wie¿y w::wierzy w
::wko³o Macieju::w ko³o Macieju
::wlasciwosci::w³aœciwoœci
::wlasnie::w³aœnie
::w³asnie::w³aœnie
::wogle::w ogóle
::wogóle::w ogóle
::wogule::w ogóle
::wokol::wokó³
::wowczas::wówczas
::wplyw::wp³yw
::wraz tym::wraz z tym
::wrzesnia::wrzeœnia
::wspo³czesne::wspó³czesne
::wspomieæ::wspomnieæ
::wsród::wœród
::wszech obecny::wszechobecny
::wszechczasów::wszech czasów
::wszytkich::wszystkich
::wszytkie::wszystkie
::wszytkim::wszystkim
::wszytko::wszystko
::wszytskich::wszystkich
::wszytskie::wszystkie
::wszytskim::wszystkim
::wszytsko::wszystko
::wy³acznie::wy³¹cznie
::wymyœleæ::wymyœliæ
::wywolana::wywo³ana
::wywolane::wywo³ane
::wzamian::w zamian
::wzd³ó¿::wzd³u¿
::wzgledu::wzglêdu
::wzi¹œæ::wzi¹æ
::wzi¹Ÿæ::wzi¹æ
::wziê³em::wzi¹³em
::wzystko::wszystko
::z du¿ej litery::du¿¹ liter¹
::z go³a::zgo³a
::z ma³ej litery::ma³¹ liter¹
::z nad::znad
::z niech::z nich
::z po miêdzy::spomiêdzy
::z pod::spod
::z pomiêdzy::spomiêdzy
::z poœród::spoœród
::z powody::z powodu itp.
::z poza::spoza
::z przed::sprzed
::z reszt¹::zreszt¹
::z wielkiej litery::wielk¹ liter¹
::z za::zza
::za miast::zamiast
::za nad to::zanadto
::za nadto::zanadto
::za raz::zaraz
::za równo::zarówno
::za zwyczaj::zazwyczaj
::zaden::¿aden
::zdechn¹³::zdech³
::zemn¹::ze mn¹
::ziemii::ziemi
::Z³odzej::Z³odziej
::znaleœæ::znaleŸæ
::znowó¿::znowu¿
::znajdizesz::znajdziesz
::zostal::zosta³
::zpoza::spoza
::zwiazek::zwi¹zek
::zwiazku::zwi¹zku
::zwlaszcza::zw³aszcza
::zycie::¿ycie
::¿adaj::¿¹daj
::¿adko::rzadko
::¿le::Ÿle
::¿ród³o::Ÿród³o
::mogla::mog³a
::powazny::powa¿ny
::stosowac::stosowaæ
::zajecia::zajêcia
::musiala::musia³a
::zobaczyla::zobaczy³a
::powiedzial::powiedzia³
::czerpa³¹::czerpa³a
::roznia::ró¿ni¹
::styli::stylów
::fir::firm
::sa::s¹
::rodzielczoœæ::rozdzielczoœæ
::lenovo::Lenovo
::rozdzielczoœc::rozdzielczoœæ
::sie::siê
::ram::RAM
::pozostale::pozosta³e
::wyposazony::wyposa¿ony
::qua::Qualcomm Snapdragon
::korzytania::korzystania
::damaszku::Damaszku
::diabel::diabe³
::wzgledów::wzglêdów
::³acz¹ca::³¹cz¹ca
::shashuka::shakshuka
::potarwy::potrawy
::cukini::cukinii
::dodakiem::dodatkiem
::grilowanym::grillowanym
::rozwiazaæ::rozwi¹zaæ
::wi¹ze::wi¹¿e
::na³o¿yc::na³o¿yæ
::znacnzie::znacznie
::sharon::Sharon
::myœla::myœl¹
::mêza::mê¿a
::sê::siê
::odchudzala::odchudza³a
::jje::jej
::odpoczywac::odpoczywaæ
::zauwazy³a::zauwa¿y³a
::chca::chc¹
::czêsciej::czêœæiej
::zmienic::zmieniæ
::spotykac::spotykaæ
::poczula::poczu³a
::znow::znów
::dbac::dbaæ
::jje::jej
::natomiat::natomiast
::przygotowala::przygotowa³a
::czesto ::czêsto
::zacze³a::zaczê³a
::wydawalo::wydawa³o
::nieporz¹dane::niepo¿¹dane
::dodawala::dodawa³a
::maslo::mas³o
::migdalowym::migda³owym
::czêœæiej::czêœciej
::ilosæ::iloœæ
::wazywa::warzywa
::energi::energii
::ktor¹::któr¹
::rozprzestrzenic::rozprzestrzeniæ
::odzywia³::od¿ywia³
::mysli::myœli
::okazalo::okaza³o
::zainteresowac::zainteresowaæ
::napiecie::napiêcie
::metode::metodê
::badzo::bardzo
::powroci³y::powróci³y
::szukac::szukaæ
::reagowac::reagowaæ
::bardoz::bardzo
::chorowala::chorowa³a
::k¹zdy::ka¿dy
::diete::dietê
::zadomowila::zadomowi³a
::watróbka::w¹tróbk¹
::mimo to,::mimo to 
::swoj::swój
::lepije::lepiej
::zauwazy³::zauwa¿y³
::zmiane::zmianê
::znalazla::znalaz³a
::glowa::g³owa
::koncu::koñcu
::wêglowodanow::wêglowodanów
::zastosownaie::zastosowanie
::poprosze::poproszê
::czlowiekiem::cz³owiekiem
::tez::te¿
::calkowicie::ca³kowicie
::dziêsi¹tki::dziesi¹tki
::za³ozy::za³o¿y
::zaczela::zaczê³a
::zamaist::zamiast
::mieœniami::miêœniami
::mozemy::mo¿emy
::osi¹gnieciu::osi¹gniêciu
::stabilnoœc::stabilnoœæ
::wazne::wa¿ne
::montazu::monta¿u
::umiesczonymi::umieszczonymi
::mó¿esz::mo¿esz
::sa::s¹
::pomoca::pomoc¹
::najbardziej korzystnych::najkorzystniejszych
::mêœ¿czyzna::mê¿czyzna
::zdecydowal::zdecydowa³
::polecila::poleci³a
::najwiekszym::najwiêkszym
::mysla³::myœla³
::mnostwo::mnóstwo
::brala::bra³a
::u¿ywac::u¿ywaæ
::pochodzacy::pochodz¹cy
::schudn¹c::schudn¹æ
::zyciu::¿yciu
::jedynei::jedynie
::mial::mia³
::nastroj::nastrój
::udalo::uda³o
::dawalo::dawa³o
::ktorym::którym
::prze³ozy³o::prze³o¿y³o
::brac::braæ
::siêgne³a::siêgnê³a
::cos::coœ
::ksia¿ce::ksi¹¿ce
::nawi¹zuja::nawi¹zuj¹
::dziêsiêæ::dziesiêæ
::przykladem::przyk³adem
::Kaliforni::Kalifornii
::wpadl::wpad³
::umysl::umys³
::róznych::ró¿nych
::zastanow::zastanów
::realizowac::realizowaæ
::przyjemnoœc::przyjemnoœæ
::srodkami::œrodkami
::sposob::sposób
::pomysl::pomys³
::sposród::spoœród
::ustalic::ustaliæ
::najwazniejszym::najwa¿niejszym
::koniecznosæ::koniecznoœæ
::wymyœleæ::wymyœliæ
::musial::musia³
::prowadze::prowadzê
::dac::daæ
::dr¹zymy::dr¹¿ymy
::wykorzytywano::wykorzystywano
::robia::robi¹
::neizbêdne::niezbêdne
::oczywiœæie::oczywiœcie
::najwazniejszych::najwa¿niejszych
::¿o³adkowych::¿o³¹dkowych
::sk³¹dników::sk³adników
::najlatwiejszych::naj³atwiejszych
::bêde::bêdê
::piêc::piêæ
::mo¿n::mo¿na
::Lolipop::Lollipop
::jakosci¹::jakoœci¹
::róznica::ró¿nica
::tlumaczenia::t³umaczenia
::chetnie::chêtnie
::jakosci::jakoœci
::mozliwoœci::mo¿liwoœci
::pomagaja::pomagaj¹
::namowiæ::namówiæ
::zamowic::zamówiæ
::tlumaczenie::t³umaczenie
::zamowi¹::zamówi¹
::t³umacyz::t³umaczy
::zamowienia::zamówienia
::jakoœc::jakoœæ
::kazdym::ka¿dym
::w³asciwego::w³aœciwego
::poslugiwanie::pos³ugiwanie
::niezaleznie::niezale¿nie
::waznych::wa¿nych
::zbie¿noœc::zbie¿noœæ
::duza::du¿a
::okreslonym::okreœlonym
::tlumaczenia::t³umaczenia
::malo::ma³o
::od³ozy³::od³o¿y³
::wiadomoœc::wiadomoœæ
::zwróc::zwróæ
::tlumacz::t³umacz
::wynikaja::wynikaj¹
::b³edy::b³êdy
::wzgledem::wzglêdem
::wyglada³a::wygl¹da³a
::Ÿródlowy::Ÿród³owy
::tlumaczeñ::t³umaczeñ
::kazdy::ka¿dy
::zamow::zamów
::wp³ywaja::wp³ywaj¹
::ci¹gly::ci¹g³y
::pewnoœc::pewnoœæ
::mieœnie::miêœnie
::Uniwersal::Universal
::Aminal::Animal
::miêsniow¹::miêœniow¹
::Uniwersal::Universal
::mieœniowej::miêœniowej
::osi¹gn¹c::osi¹gn¹æ
::kótra::która
::substnacji::substancji
::tkóre::które
::miêsniowych::miêœniowych
::miêsniowych::miêœniowych
::miêsniom::miêœniom
::najwazniejsz¹::najwa¿niejsz¹
::jesli::jeœli
::czeœæiowy::czêœciowy
::czêœæiowy::czêœciowy
::p³¹tnym::p³atnym
::publicznoœæi::publicznoœCi
::zê::¿e
::jestes::jesteœ
::wiêkszosæi::wiêkszoœci
::szczêœæie::szczêœcie
::najczêœæiej::najczêœciej
::dopuki::dopóki
::sk³¹dzie::sk³adzie
::mieœniom::miêœniom
::po³aczeniu::po³¹czeniu
::bialek::bia³ek
::miesni::miêœni
::œa::s¹
::mieœniowa::miêœniowa
::dostepny::dostêpny
::miêsniowej::miêœniowej
::srodka::œrodka
::cieszyc::cieszyæ
::æwicza::æwicz¹
::zabrac::zabraæ
::d³uzej::d³u¿ej
::miêsniom::miêœniom
::dotycza::dotycz¹
::swiadczenie::œwiadczenie
::z³o¿yc::z³o¿yæ
::zaczeli::zaczêli
::tlumaczeniowa::t³umaczeniowa
::kazdego::ka¿dego
::tworzylo::tworzy³o
::tworza::tworz¹
::wiêkszoœc::wiêkszoœæ
::najwazniejsze::najwa¿niejsze
::najwazniejsze::najwa¿niejsze
::prêdkoœc::prêdkoœæ
::najwazniejszych::najwa¿niejszych
::indiach::Indiach
::pochodza::pochodz¹
::zapoznac::zapoznaæ
::jezyków::jêzyków
::mozliwosæ::mo¿liwoœæ
::tlumaczenia::tlumaczenia
::tysiecy::tysiêcy
::jakóœæ::jakoœæ
::uwazaj¹::uwa¿aj¹
::urzadzenia::urz¹dzenia
::wp³yn¹c::wp³yn¹æ
::wp³ywaja::wp³ywaj¹
::wziêly::wziê³y
::przypomniec::przypomnieæ
::zastapiæ::zast¹piæ
::dzia³aja::dzia³aj¹
::znaleŸc::znaleŸæ
::chesz::chcesz
::zaangazuj::zaanga¿uj
::dopisac::dopisaæ 
::odnosza::odnosz¹
::zagrac::zagraæ
::wartoœc::wartoœæ
::uslugi::us³ugi
::rozwi¹zywac::rozwi¹zywaæ
::reklame::reklamê
::zaangazujesz::zaanga¿ujesz
::zdolnoœc::zdolnoœæ
::wazniejsze::wa¿niejsze
::b³edem::b³êdem
::mozliwoœæ::mo¿liwoœæ
::najczeœciej::najczeœciej
::wplywaj¹::wp³ywaj¹
::firme ::firmê
::wypuntowanych::wypunktowanych
::pytaja::pytaj¹
::ró¿ne::ró¿ne
::zachowac::zachowaæ
::...::…
::zajmuja::zajmuj¹
::wazniejszy::wa¿niejszy
::osi¹gn¹c::osi¹gn¹æ
::dostala::dosta³a
::wygl¹dala::wygl¹da³a
::jezyki::jêzyki
::storny::strony
::prze³umaczy³o::przet³umaczy³o
::zaangazowanie::zaanga¿owanie
::zaangazowanie::zaanga¿owanie
::moze::mo¿e
::stornê::stronê
::storna::strona
::maszyne::maszynê
::maszyne::maszynê
::s³u¿yc::s³u¿yæ
::jezykow¹::jêzykow¹
::mialo::mia³o
::wystarczajaco::wystarczaj¹co
::zastapi¹::zast¹pi¹
::jakóœc::jakoœæ
::zagrozonych::zagro¿onych
::wiêkszoœc::wiêkszoœæ
::czêœæi::czêœci
::stornie::stronie
::najwazniejszymi::najwa¿niejszymi
::marta::Marta
::pieniedzy::pieniêdzy
::z³osliwego::z³osliwego
::zamowi³::zamówi³
::bêdac::bêd¹c
::polsce::Polsce
::pracuja::pracuj¹
::pokazywac::pokazywaæ
::jesli::jeœli
::póxno::póŸno
::okreslonej::okreœlonej
::pisalismy::pisaliœmy
::ksi¹zek::ksi¹¿ek
::dostepne::dostêpne
::bêda::bêd¹
::zaanwansowanego::zaawansowanego
::radza::radz¹
::chca::chc¹
::jêœli::jêœli
::zamówic::zamówiæ
::zamowily::zamówi³y
::najwazniejszego::najwa¿niejszego
::rozwiazañ::rozwi¹zañ
::powieksza³y::powiêksza³y
::wyspecjalizowac::wyspecjalizowaæ
::stalo::sta³o
::storn::stron
::wywiazywa³o::wywi¹zywa³o
::polacy::Polacy
::tlumaczysz::t³umaczysz
::zgloszeñ::zg³oszeñ
::mnóœtwo::mnóstwo
::najwieksze::najwiêksze
::dzien::dzieñ
::najw¹¿niejszej::najwa¿niejszej
::zgodnei::zgodnie
::zamowi¹::zamówi¹
::zaplaci::zap³aci
::dizeki::dziêki
::okreslony::okreœlony
::wysy³ac::wysy³aæ
::jêœli::jeœli
::kleinta::klienta
::bierz¹cych::bie¿¹cych
::baze::bazê
::usun¹c::usun¹æ
::otrzymac::otrzymaæ
::tworzyc::tworzyæ
::sa::s¹
::tkóry::który
::czêœc::czêœæ
::trudnoœc::trudnoœæ
::omin¹c::omin¹æ
::znakow::znaków
::zalo¿yæ::za³o¿yæ
::najw¹¿niejszych::najwa¿niejszych
::jakas::jakaœ
::najgroszych::najgorszych
::myslisz::myœlisz
::mó¿liwoœc::mo¿liwoœæ
::wiêkszoœc::wiêkszoœæ
::sprawdzac::sprawdzaæ
::uzywaj¹::u¿ywaj¹
::duzy::du¿y
::szczególy::szczegó³y
::³umaczeñ::t³umaczeñ
::czesto::czêsto
::tê¿::te¿
::odrywac::odrywaæ
::teks::tekst
::zostala::zosta³a
::urzadzenie::urz¹dzenie
::czêœto::czêsto
::polaków::Polaków
::uniknac::unikn¹æ
::moglaby::mog³aby
::osob::osób
::zwróca::zwróc¹
::twojej::Twojej
::twoja::Twoja
::twoje::Twoje
::bêdizesz::bêdziesz
::ciê::Ciê
::firme::firmê
::zdjêæia::zdjêcia
::caly::ca³y
::posiadal::posiada³
::rozdzielczoœæi¹::rozdzielczoœci¹
::najwazniejszy::najwa¿niejszy
::wyposazona::wyposa¿ona
::pamieci¹::pamiêci¹
::przetlumaczeniu::przet³umaczeniu
::twojego::Twojego
::doswiadczenia::doœwiadczenia
::caloœci::ca³oœci
::czytelnikow::czytelników
::pomiedzy::pomiêdzy
::rz¹daj¹::¿¹daj¹
::tlumaczeniowym::t³umaczeniowym
::jakóœci¹::jakoœci¹
::rz¹da::¿¹da
::namowienie::namówienie
::tlumaczeñ::t³umaczeñ
::zostalo::zosta³o
::dlugoterminowych::d³ugoterminowych
::rozgl¹dac::rozgl¹daæ
::szczegolnie::szczególnie
::potwórzenia::powtórzenia
::Ÿródel::Ÿróde³
::zauwazy³eœ::zauwa¿y³eœ
::krokow::kroków
::zamowienie::zamówienie
::tlumaczy::t³umaczy
::zaplaty::zap³aty
::je¿d¿a::je¿d¿¹
::d³ugoœæi::d³ugoœci
::æwiczyc::æwiczyæ
::zwiekszajacy::zwiêkszajacy
::me¿czyzn::mê¿czyzn
::mieœni::miêœni
::byly::by³y
::nawi¹zesz::nawi¹¿esz
::stawal::stawa³
::pieniadze::pieni¹dze
::pamieæ::pamiêæ
::sa::s¹
::upadloœæ::upad³oœæ
::koñcza::koñcz¹
::sprzedazowe::sprzeda¿owe
::umiejêtnóœciami::umiejêtnoœciami
::wracal::wraca³
::podci¹gn¹c::podci¹gn¹æ
::komorkowy::komórkowy
::ci¹glych::ci¹g³ych
::duzych::du¿ych
::waznego::wa¿nego
::waznymi::wa¿nymi
::skutecznosc::skutecznoœæ
::zapisac::zapisaæ
::zapisac::zapisaæ
::jezykach::jêzykach
::tlumaczenia::t³umaczenia
::ponosza::ponosz¹
::póxniej::póŸniej
::wy³acza::wy³¹cza
::wyposazone::wyposa¿one
::zapomniec::zapomnieæ
::rozwa¿yc::rozwa¿yæ
::dzialaj¹::dzia³aj¹
::dlu¿ej::d³u¿ej
::p³acic::p³aciæ
::jeydnie::jedynie
::trasfery::transfery
::wiêkszoœc::wiêkszoœæ
::laciny::³aciny
::waznym::wa¿nym
::znajomóœæ::znajomoœæ
::u¿ywac::u¿ywaæ
::Ÿródlowe::Ÿród³owe
::wybierac::wybieraæ
::rz¹daæ::¿¹daæ
::rozbudowac::rozbudowaæ
::antyafsda::antykataboliczne
::Zaiwera::Zawiera
::trenigów::treningów
::trenuja::trenuj¹
::miêœnoiwej::miêœniowej
::wspomorze::wspomo¿e
::skutecnza::skuteczna
::nastomiast::natomiast
::wchodzilo::wchodzi³o
::wrecz::wrêcz
::myœle::myœlê
::polskê::Polskê
::uzywania::u¿ywania
::s³¹bszy::s³abszy
::mia³¹::mia³a
::tyl::ty³
::bed¹::bêd¹
::malymi::ma³ymi
::liczyc::liczyæ
::jasnoœc::jasnoœæ
::gruboœc::gruboœæ
::wskazuja::wskazuj¹
::uzytkownika::u¿ytkownika
::siêci::sieci
::koniecznoœc::koniecznoœæ
::c¿esto::czêsto
::zauwazy::zauwa¿y
::wyczuce::wyczucie
::napisac::napisaæ
::wiedyz::wiedzy
::latwiejsze::³atwiejsze
::zagl¹dac::zagl¹daæ
::tlumaczenie::t³umaczenie
::bardziej odporni::odporniejsi
::wyzej::wy¿ej
::zaangazowane::zaanga¿owane
::napiec::napiêæ
::produtków::produktów
::wzbudzal::wzbudza³
::Zwróc::Zwróæ
::publicznoœc::publicznoœæ
::pisza::pisz¹
::diza³a::dzia³a
::sprzedazy::sprzeda¿y
::nawi¹z¹æ::nawi¹zaæ
::pan::Pan
::wrzuce::wrzucê 
::wysy³aja::wysy³aj¹ 
::pan::Pan
::dodac::dodaæ
::dziekuje::dziêkujê
::pchn¹c::pchn¹æ
::teksy::teksty
::œnieznobia³ego::œnie¿nobia³ego
::mieœniowych::miêœniowych
::³aczy::³¹czy
::mieœnie::miêœnie
::zwiekszaj¹::zwiêkszaj¹
::zwiekszyæ::zwiêkszyæ
::wplywa::wp³ywa
::ilóœæ::iloœæ
::po³¹cznie::po³¹czenie
::oœób::osób
::rozpuszczalnoœc::rozpuszczalnoœæ
::regenracjê::regeneracjê
::rodzajow::rodzajów
::odzywczych::od¿ywczych
::poracja::porcja
::uzupe³nic::uzupe³niæ
::wydajnosæ::wydajnoœæ 
::ksi¹¿ke::ksi¹¿kê
::zaangazowanie::zaanga¿owanie
::kóry::który
::dok³adnoœc::dok³adnoœæ
::dokladnie::dok³adnie
::nastapiæ::nast¹piæ
::dzialo::dzia³o
::pomys³ow::pomys³ów
::angazujesz::anga¿ujesz
::dziala::dzia³a
::iloœæi::iloœci
::pozostawac::pozostawaæ
::miesiecy::miesiêcy
::osi¹galy::osi¹ga³y
::r1::®
::moge::mogê
::oglada::ogl¹da
::takze::tak¿e
::po³aczyæ::po³¹czyæ
::urz¹dzen::urz¹dzeñ
::mózna::mo¿na
::usludze::us³udze
::wygl¹dalo::wygl¹da³o
::zmniejszyc::zmniejszyæ
::Zrównowazony::Zrównowa¿ony
::karme::karmê
::siemie::siemiê
::iloœcia::iloœci¹
::bozita::Bozita
::œwie¿oœc::œwie¿oœæ
::róznej::ró¿nej
::miesa::miêsa
::malego::ma³ego
::psow::psów
::s³u¿a::s³u¿¹
::jedza::jedz¹
::tluszczem::t³uszczem
::miêœa::miêsa
::mieso::miêso
::regulujacy::reguluj¹cy
::aktywnoœc::aktywnoœæ
::œwiezoœci¹::œwie¿oœci¹
::zawartoœc::zawartoœæ
::zamykac::zamykaæ
::obawiac::obawiaæ
::kotow::kotów
::œwiezoœci::œwie¿oœci
::przechowywac::przechowywaæ
::Iso::ISO
::G³ownym::g³ównym
::zgnieœc::zgnieœæ
::kawalki::kawa³ki
::malych::ma³ych
::sklad::sk³ad
::wolowe::wo³owe
::szwecji::Szwecji
::jakóœci::jakoœci
::zarowno::zarówno
::wiêkszóœci::wiêkszoœci
::sk³¹d::sk³ad
::dostarczaj¹æej::dostarczaj¹cej
::nalezy::nale¿y
::slu¿¹::s³u¿¹
::mieœa::miêsa
::wp³ywajacego::wp³ywaj¹cego
::nadwage::nadwagê
::o3::Omega-3
::o6::Omega-6
::Macrogard:: MacroGard® 
::odpornosc::odpornoœæ
::odzywcze::od¿ywcze
::cierpiacych::cierpi¹cych
::Najwazniejszymi::Najwa¿niejszymi
::wyjatkowo::wyj¹tkowo
::pracujacych::pracuj¹cych 
::jakósci::jakoœci
::wywo³ywac::wywo³ywaæ
::chronia::chroni¹
::sa::s¹
::w³asciwoœci::w³aœciwoœci
::psób::psów
::przechodza::przechodz¹
::prawidlowego::prawid³owego
::zawartoœc::zawartoœæ
::wywo³uja::wywo³uj¹
::sk³¹dniki::sk³adniki
::zabraklo::zabrak³o
::wlaœcicieli::w³aœcicieli
::antyoksydantow::antyoksydantów
::calym::ca³ym
::nastêpujace::nastêpuj¹ce
::kilogramow::kilogramów
::takzê::tak¿e
::prolbemy::problemy
::pokarmow::pokarmów
::powyzej::powy¿ej
::wa¿acym::wa¿¹cym
::œwiezy::œwie¿y
::mo¿liwoœc::mo¿liwoœæ
::zaanwansowanych::zaawansowanych
::umiejetnoœci::umiejêtnoœci
::milionow::milionów
::rozwijac::rozwijaæ
::u¿yc::u¿yæ
::uzyskac::uzyskaæ
::okolo::oko³o
::opóxniona::opóŸniona
::rózni::ró¿ni
::rzetony::¿etony
::wsyzstko::wszystko
::rzetonów::¿etonów
::pasowal::pasowa³
::naœladowal::naœladowa³
::pozna³es::pozna³eœ
::nosza::nosz¹
::pasowala::pasowa³a
::Holdem::Hold'em
::protszym::prostszym
::oferuja::oferuj¹
::po³owe::po³owê
::stworza::stworz¹
::mo¿ña::mo¿na
::spotkac::spotkaæ
::mozesz::mo¿esz
::poznac::poznaæ
::rozwiazaniem::rozwi¹zaniem
::umiejêtnóœæ::umiejêtnoœæ
::slabe::s³abe
::wybrac::wybraæ
::trwaloœc::trwa³oœæ
::wyró¿niaja::wyró¿niaj¹
::powodujacych::powoduj¹cych
::wplywaj¹cy::wp³ywaj¹cy
::mieso::miêso
::uslugom::us³ugom
::ilosci¹::iloœci¹
::sprawiac::sprawiaæ
::maly::ma³y
::wiêkszoœc::wiêkszoœæ
::równiêz::równie¿
::wymienilismy::wymieniliœmy
::widzialeœ::widzia³eœ
::musze::muszê
::wymyœlec::wymyœliæ
::przekonac::przekonaæ
::kwote::kwotê
::spólek::spó³ek
::karte::kartê
::wygrywac::wygrywaæ
::wymagaja::wymagaj¹
::nauczyc::nauczyæ
::wplacaæ::wp³acaæ
::kazdej::ka¿dej
::mozesz::mo¿esz 
::dotyczacej::dotycz¹cej
::czesto::czêsto
::pamietaæ::pamiêtaæ
::mo¿liwoœc::mo¿liwoœæ
::poprawi¹j¹::poprawiaj¹
::wartosciowe::wartoœciowe
::pozwalajac¹::pozwalaj¹c¹
::miesniowej::miêœniowej
::przyjeciu::przyjêciu
::odzywka::od¿ywka
::odpornosæ::odpornoœæ
::problemow::problemów
::mê¿æzyzn::mê¿czyzn
::æwiczen::æwiczeñ
::dostarczaj¹æa::dostarczajaca
::miesniow¹::miêœniow¹
::wytrzymaloœæ::wytrzyma³oœæ
::moca::moc¹
::sily::si³y
::zawartosæ::zawartoœæ
::latwa::³atwa
::odzywiaj¹ce::od¿ywiaj¹ce
::najwazniejsza::najwa¿niejsza
::budowac::budowaæ
::zadziala::zadziala
::si³e::si³ê
::cwiczenia::æwiczenia
::æwiczyc::æwiczyæ
::zwiekszaj¹ce::zwiêkszaj¹ce
::wydajnoœc::wydajnoœæ
::popularnoœc::popularnoœæ
::osi¹gneli::osi¹gnêli
::pragna::pragn¹
::angazowania::anga¿owania
::przedsiêbiorczosci::przedsiêbiorczoœci
::wynosza::wynosz¹
::okolicznoœæi::okolicznoœCi
::smartona::smartfona
::przelo¿yæ::prze³o¿yæ
::po³aczone::po³¹czone
::wazny::wa¿ny
::dŸwiekowa::dŸwiêkowa
::dŸwiek::dŸwiêk
::mogly::mog³y
::dxwiêkowa::dŸwiêkowa
::dŸwieku::dŸwiêku
::nosic::nosiæ
::dŸwiekowe::dŸwiêkowe
::dŸwiekow¹::dŸwiêkow¹
::g³osniki::g³oœniki
::iloœæi¹::iloœci¹
::pojawiaja::pojawiaj¹
::œróba::œruba
::szczególowe::szczegó³owe
::pozbyc::pozbyæ
::skorê::skórê
::uzywamy::u¿ywamy
::odpowiedx::odpowiedŸ
::zaangazowaniu::zaanga¿owaniu
::dlugo::d³ugo
::wydrukow::wydruków
::cene::cenê
::wiêkszoœc::wiêkszoœæ
::nalezy::nale¿y
::drukarke::drukarkê
::szybkoœc::szybkoœæ
::mobilnoœc::mobilnoœæ
::sa::s¹
::zdjeæ::zdjêæ
::drukowac::drukowaæ
::pojemnoœc::pojemnoœæ
::sa::s¹
::mo¿liwoœc::mo¿liwoœæ
::skoñcza::skoñcz¹
::wiêkszosæ::wiêkszoœæ
::wifi::Wi-Fi
::ka¿ego::ka¿dego
::pozwalaja::pozwalaj¹
::przeprowadzajace::przeprowadzajace
::porozmawiac::porozmawiaæ
::tlumaczenie::t³umaczenie
::zostaly::zosta³y
::miales::mia³eœ
::odzywczych::od¿ywczych
::skóre::skórê
::zastosowac::zastosowaæ
::poprawic::poprawiæ
::masazu::masa¿u
::opóxnienia::opóŸnienia
::poŸniej::póŸniej
::gre::grê
::przeziebienie::przeziêbienie
::tlumacza::t³umacza
::okreslone::okreœlone
::stalego::sta³ego
::tlumaczeniu::t³umaczeniu
::okreœlic::okreœliæ
::okreslaniu::okreœlaniu
::skorzystac::skorzystaæ
::uwaznie::uwa¿nie
::zauwazymy::zauwa¿ymy
::rózne::ró¿ne
::poslugujesz::pos³ugujesz
::pod¹¿¹j¹::pod¹¿aj¹
::najczêœæiej::najczêœciej
::przyk³¹d::przyk³ad
::¿o³adka::¿o³¹dka
::mieœniowe::miêœniowe
::dzia³¹nie::dzia³anie
::nieporz¹danych::niepo¿¹danych
::ciêzko::ciê¿ko
::pote¿ny::potê¿ny
::za³aczniku::za³¹czniku
::wieksza::wiêksza
::uzy³em::u¿y³em
::poznawac::poznawaæ
::porzadku::porz¹dku
::manuka::Manuka
::zebów::zêbów
::witalnoœc::witalnoœæ
::wlosów::w³osów
::dzialañ::dzia³añ 
::jezykowym::jêzykowym
::poprzestac::poprzestaæ
::zdenerowaæ::zdenerwowaæ
::osi¹gniecia::osi¹gniêcia
::pochodza::pochodz¹
::najprotszych::najprotszych
::troche::trochê
::sprawe::sprawê
::przeciwieñœtwie::przeciwieñstwie
::syzbko::szybko
::³ykac::³ykaæ
::trenujacych::trenuj¹cych
::wplywaj¹cych::wp³ywaj¹cych
::ilosc::iloœæ
::w³aœciwoœæi::w³aœciwoœci
::przecietny::przeciêtny
::bie¿aco::bie¿¹co
::ksia¿ek::ksi¹¿ek
::zaskakujacym::zaskakuj¹cym
::s³ow::s³ów
::zaanga¿owac::zaanga¿owaæ
::zaangazowaæ::zaanga¿owaæ
::treœcia::treœci¹
::substacji::substancji
::dawac::dawaæ
::wskazywac::wskazywaæ
::powazn¹::powa¿n¹
::siêgn¹c::siêgn¹æ
::trenowac::trenowaæ
::pozytecznych::po¿ytecznych
::odzywcych::od¿ywczych
::wazniejsi::wa¿niejsi
::szczeœæie::szczêœcie
::kazde::ka¿de
::dzia³an::dzia³añ
::dodawac::dodawaæ
::salatek::sa³atek
::spo³êczeñstwa::spo³eczeñstwa
::krakowa::Krakowa
::apartamen::apartament
::otyloœci::oty³oœci
::znajduja::znajduj¹
::¿ê::¿e
::eksluzywne::ekskluzywne
::wychodza::wychodz¹
::popelniaj¹::pope³niaj¹
::wlasnej::w³asnej
::bêdziê::bêdzie
::dziekujê::dziêkujê
::zabijaja::zabijaj¹
::¿o³adku::¿o³¹dku
::szczêscie::szczêœcie
::poruszac::poruszaæ
::indeksowac::indeksowaæ
::treœæi::treœci
::³¹czacym::³¹cz¹cym
::sa::s¹
::klikn¹c::klikn¹æ
::konkurowac::konkurowaæ
::komentowac::komentowaæ
::zwiekszenie::zwiêkszenie
::zwiekszy::zwiêkszy
::uchronic::uchroniæ
::unikn¹c::unikn¹æ
::przechódŸ::przechodŸ
::odzywiania::od¿ywiania
::odzywczych::od¿ywczych
::skupic::skupiæ
::przywiazuje::przywi¹zuje
::wiêkszosc::wiêkszoœæ
::mysza::mysz¹
::android::Android
::androidem::Androidem
::pozbyc::pozbyæ
::budowe::budowê
::tanszym::tañszym
::kostke::kostkê
::zlotych::z³otych
::udac::udaæ
::zweryfikowac::zweryfikowaæ
::przypominac::przypominaæ
::wazna::wa¿na 
::wiêkszosci::wiêkszoœci
::sprzet::sprzêt
::badanai::badania
::spowoli::spowolni
::wyciszaj¹æy::wyciszaj¹cy
::kopozycjê::kompozycjê
::rozluŸna::rozluŸnia
::problami::problemami
::najprotszym::najprostszym
::niewielke::niewielkie
::nawte::nawet
::zak³¹daj¹::zak³adaj¹
::obci¹zeniem::obci¹¿eniem
::cie¿arach::ciê¿arach
::wymagajace::wymagaj¹ce
::osiagn¹æ::osiagn¹æ
::osiagn¹æ::osi¹gn¹æ
::póxniejsze::póŸniejsze
::marzyleœ::marzy³eœ
::odm³adzajace::odm³adzaj¹ce
::niepo¿adane::niepo¿¹dane
::pamieci::pamiêci
::stawyw::statyw
::ciêzkiego::ciê¿kiego
::obci¹zenia::obci¹¿enia
::stawywu::statywu
::kosztuja::kosztuj¹
::od³o¿yc::od³o¿yæ
::mo¿liwoœc::mo¿liwoœæ
::srodkiem::œrodkiem
::wydajnoœæi::wydajnoœci
::Ssd::SSD
::wymagajacych::wymagaj¹cych
::miêsniowego::miêœniowego
::osiagn¹c::osi¹gn¹æ
::osiagnaæ::osi¹gn¹æ
::dzia³¹::dzia³a
::dotykac::dotykaæ
::wspólpracowaæ::wspó³pracowaæ
::czlowiek::cz³owiek
::przyciagniemy::przyci¹gniemy
::pozytecznie::po¿ytecznie
::³¹twych::³atwych
::³¹twiej::³atwiej
::wartosci::wartoœci
::chorobe::chorobê
::cie¿arami::ciê¿arami
::szukajace::szukaj¹ce
::rózne::ró¿ne
::spodziewac::spodziewaæ
::swietnym::œwietnym
::gb::GB
::wyposazono::wyposa¿ono
::g³osników::g³oœników
::wygrac::wygraæ
::czytac::czytaæ
::widzia³es::widzia³eœ
::rêke::rêkê
::wyeliminowac::wyeliminowaæ
::uzywaj¹c::u¿ywaj¹c
::podj¹c::podj¹æ
::œwiete::œwiête
::wspomoga::wspomog¹
::wykonywac::wykonywaæ
::osiagamy::osi¹gamy
::zapominac::zapominaæ
::ciêzar::ciê¿ar
::zapisywac::zapisywaæ
::ulegac::ulegaæ
::pamietac::pamiêtaæ
::powodowac::powodowaæ
::uniknaæ::unikn¹æ
::wytrzyma³oœc::wytrzyma³oœæ
::pewnosæ::pewnoœæ
::przek³adac::przek³adaæ
::podgrzac::podgrzaæ
::wypóbuj::wypróbuj
::podnosic::podnosiæ
::zwiekszyæ::zwiêkszyæ
::mozesz::mo¿esz
::po³aczony::po³¹czony
::zaangazowaniem::zaanga¿owaniem
::wp³ywac::wp³ywaæ
::wp³yn¹c::wp³yn¹æ
::kosci::koœci
::powiazane::powi¹zane
::pote¿nym::potê¿nym
::ksia¿kê::ksi¹¿kê
::b³edów::b³êdów
::czeœciej::czêœciej
::b³ad::b³¹d
::niecheæ::niechêæ
::róznice::ró¿nice
::widac::widaæ
::rzadkoœcia::rzadkoœci¹
::sprawic::sprawiæ
::Ÿród³e³::Ÿróde³
::zauwa¿yc::zauwa¿yæ
::stac::staæ
::przepisywac::przepisywaæ
::zwizualizowac::zwizualizowaæ
::jestesmy::jesteœmy
::przewidywac::przewidywaæ
::podœwiadomoœc::podœwiadomoœæ
::wynikajace::wynikaj¹ce
::negocjowac::negocjowaæ
::w³asnie::w³aœnie
::umiejêtnosæ::umiejêtnoœæ
::okreslon¹::okreœlon¹
::ogladaj¹c::ogl¹daj¹æ
::opracowal::opracowa³
::zaangazowanych::zaanga¿owanych
::ukrywac::ukrywaæ
::wyjasni³a::wyjaœni³a
::koncetrowaæ::koncentrowaæ
::robie::robiê
::pozostac::pozostaæ
::decyzyjnoœc::decyzyjnoœæ
::odpowiedzialnoœc::odpowiedzialnoœæ
::osi¹gneliœmy::osi¹gnêliœmy
::iloœc::iloœæ
::przejsæ::przejœæ
::menagerami::managerami
::biora::bior¹
::narzekac::narzekaæ
::zapobiegac::zapobiegaæ
::odzywczymi::od¿ywczymi
::¿ywnosæ::¿ywnoœæ
::wlaœnie::w³aœnie
::poglad::pogl¹d
::takze::tak¿e
::pojawiac::pojawiaæ
::pokazaly::pokaza³y
::przerazony::przera¿ony
::glowie::glowie
::wpadac::wpadaæ
::dopasowac::dopasowaæ
::osiagn¹æ::osi¹gn¹æ
::kolejncyh::kolejnych
::kamila::Kamila
::kamili::Kamili
::monika::Monika
::pokonac::pokonaæ
::mowi::mówi
::z³ozy³::z³o¿y³
::³amliwoœc::³amliwoœæ
::krwioobiegu::krwiobiegu
::wch³anialnoœc::wch³anialnoœæ
::mo¿ê::mo¿e
::pracowalem::pracowa³em
::krwionosnych::krwionoœnych
::ogrod::ogród
::niemiec::Niemiec
::¿o³adkiem::¿o³¹dkiem
::wiêkszoœc::wiêkszoœæ
::dlugi::d³ugi
::, jak::  jak
::uzywaæ::u¿ywaæ
::skutecznoœc::skutecznoœæ
::obni¿yc::obni¿yæ
::odzywia³em::od¿ywia³em
::uprawiac::uprawiaæ
::temu, nie::temu nie
::cie¿ar::ciê¿ar
::temu, uzupe³nisz::temu uzupe³nisz
::cwiczenie::æwiczenie
::niej, mo¿esz::niej mo¿esz
::niej, rozwijamy::niej rozwijamy
::cwiczeñ::æwiczeñ
::miêsnie::miêœnie
::slady::œlady
::miêsnie::miêœnie
::wydajnosci::wydajnoœci
::rzêŸbê::rzeŸbê
::bêda::bêd¹
::, pozwala:: pozwala
::póxnym::póŸnym
::, ni¿:: ni¿
::g³ownych::g³ównych
::odpornoœc::odpornoœæ
::dzia³an::dzia³añ
::marnuja::marnuj¹
::powaznym::powa¿nym
::lekcewarzyæ::lekcewa¿yæ
::pracowac::pracowaæ
::bardizej::bardziej
::denerwowac::denerwowaæ
::powinienes::powinieneœ
::zmus::zmuœ
::niewlaœciwe::niew³aœciwe
::przyjrzec::przyjrzeæ
::¿o³adka::¿o³¹dka
::rodzielczoœc::rozdzielczoœæ
::pobra³es::pobra³eœ
::eksperymentowac::eksperymentowaæ
::dostosowac::dostosowaæ
::edytowac::edytowaæ
::po³acznie::po³¹czenie
::nowoœc::nowoœæ
::skupily::skupi³y
::w³aœciwóœci::w³aœciwoœci
::badan::badañ
::, ni¿:: ni¿
::me¿czyznach::mê¿czyznach
::intensywnoœc::intensywnoœæ
::po³aczeniem::po³¹czeniem
::roslin¹::roœlin¹
::w³aœciwosciami::w³aœciwoœciami
::ryzykowac::ryzykowaæ
::smazony::sma¿ony
::podrózy::podró¿y
::odzywiaæ::od¿ywiaæ
::wode::wodê
::iloœc::iloœæ
::wytrzyma³oœc::wytrzyma³oœæ
::tluszczu::t³uszczu
::przyswalajn¹::przyswajaln¹
::sa::s¹
::spozywamy::spo¿ywamy
::powazne::powa¿ne
::póxniejszym::póŸniejszym
::jesli::jeœli
::opowiadac::opowiadaæ godzinami
::pisac::pisaæ
::prze³ozyæ::prze³o¿yæ
::nalezy::nale¿y
::pryzk³ad::przyk³ad
::okresliæ::okreœliæ
::wyizolowac::wyizolowaæ
::porównac::porównaæ
::narazeni::nara¿eni
::odzywienie::od¿ywienie
::ocie¿a³y::ociê¿a³y
::dojsæ::dojœæ
::cwiczysz::æwiczysz
::hleb::chleb
::stymulowac::stymulowaæ
::synteze::syntezê
::d³ugotrwalego::d³ugotrwa³ego
::przynosza::przynosz¹
::posilków::posi³ków
::musza::musz¹
::dolegliwoœc::dolegliwoœæ
::p³odnoœc::p³odnoœæ
::preparatow::preparatów
::przywrócic::przywróciæ
::wzmocnic::wzmocniæ
::liœc::liœæ
::masci::maœci
::rosliny::roœliny
::uzywane::u¿ywane
::Brazyli::Brazylii
::skorzytaæ::skorzystaæ
::plemie::plemiê
::pos³uzyæ::pos³u¿yæ
::postepuje::postêpuje
::slodki::s³odki
::wiêkszoœc::wiêkszoœæ
::srodków::œrodków
::odnosnie::odnoœnie
::opierac::opieraæ
::przyk³¹dowo::przyk³adowo
::odzywianiem::od¿ywianiem
::zabrac::zabraæ
::wrazliwa::wra¿liwa
::pieknym::piêknym
::dŸwieków::dŸwiêków
::patrzec::patrzeæ
::podlogi::pod³ogi
::doroslych::doros³ych
::najmlodszych::najm³odszych
::bawia::bawi¹
::krwionosny::krwionoœny
::podawac::podawaæ
::cierpliwoœc::cierpliwoœæ
::tkanke::tkankê
::dluga::d³uga
::zamknêly::zamknê³y
::stosowac::stosowaæ
::wiêkszosc::wiêkszoœæ
::dbala::dba³a
::mialy::mia³y
::rosji::Rosji
::przyrode::przyrodê
::powstal::powsta³
::niechêc::niechêæ
::zostaly::zosta³y
::zaczêla::zaczê³a
::kadluba::kad³uba
::wykorzystywac::wykorzystywaæ
::niemców::Niemców
::pilotarzu::pilota¿u
::pilotarzem::pilota¿em
::zachowal::zachowa³
::wzg³êdu::wzglêdu
::zwrotnoœc::zwrotnoœæ
::walke::walkê
::soji::soi
::póxnych::póŸnych
::przekasek::przek¹sek
::poprawic::poprawiæ
::bialka::bia³ka 
::masujaca::masuj¹ca
::spróbowac::spróbowaæ
::narazone::nara¿one
::z³acz::z³¹cz
::g³osnika::g³oœnika
::lodówke::lodówkê
::prad::pr¹d
::urzadzeñ::urz¹dzeñ
::opóxniæ::opóŸniæ
::wysokoœc::wysokoœæ
::poszukac::poszukaæ
::okreslonym::okreœlonym
::uzywanie::u¿ywanie
::pozwalajace::pozwalajace
::czêœæiach::czêœciach
::Panstwa::Pañstwa
::dosc::doœæ
::wykopywac::wykopywaæ
::slonecznym::s³onecznym
::pieknie::piêknie
::zaleznoœci::zale¿noœci
::ciesza::ciesz¹
::sa::s¹ 
::piekne::piêkne
::pieknego::piêknego
::g³êbokoœc::g³êbokoœæ
::holera::cholera
::wypytac::wypytaæ
::kleint::klient
::daltego::dlatego
::udzielajacych::udzielaj¹cych\
::zwrociæ::zwróciæ
::uratowac::uratowaæ
::umowe::umowê
::gdzies::gdzieœ
::mog³::móg³
::zaleg³oœc::zaleg³oœæ
::sprzetu::sprzêtu
::soba::sob¹
::przyjmowac::przyjmowaæ
::zwiêkszyc::zwiêkszyæ
::suplementow::suplementów
::mysl¹::myœl¹
::wydobyc::wydobyæ
::odbudowywac::odbudowywaæ
::VITARGO::VITARGO®
::d³uzsze::d³u¿sze
::konopii::konopi
::dziure::dziurê
::skoncetrowanych::skoncentrowanych
::uwazam::uwa¿am
::uwazam::uwa¿am
::wyrózni::wyró¿ni
::rozdzielczosci::rozdzielczoœci
::dziela::dziel¹
::podrózuj¹::podró¿uj¹
::Hdd::HDD
::gloœników::g³oœników
::sluchania::s³uchania
::malym::ma³ym
::cie¿arowych::cêe¿arowych
::uk³¹d::uk³ad
::zdobywac::zdobywaæ
::alergi::alergii
::parti::partii
::wspo³pracuj¹::wspó³pracuj¹
::tak¿ê::tak¿e
::nauczylismy::nauczyliœmy
::wiekszoœc::wiêkszoœæ
::spo¿ywac::spo¿ywaæ
::ciêzarem::ciê¿arem
::kursantow::kursantów
::korzysci::korzyœci
::dostep::dostêp
::odbierac::odbieraæ
::kra¿ênie::kr¹¿enie
::ciêzkich::ciê¿kich
::skórcze::skurcze
::zwiekszona::zwiêkszona
::obrzeków::obrzêków
::najwazniejsze::najwa¿niejsze
::elastycznoœc::elastycznoœæ
::gardlo::gard³o
::poprawe::poprawê
::dolegliwoœæi::dolegliwoœCi
::desing::design
::œledzic::œledziæ
::zwieksz::zwiêksz
::dolarow::dolarów
::bêda::bêd¹
::porz¹dan¹::po¿¹dan¹
::zamowieñ::zamówieñ
::ksia¿ki::ksi¹¿ki
::usiadŸ::usi¹dŸ
::osi¹gnaæ::osi¹gn¹æ
::i¿::¿e
::najwazniejsze::najwa¿niejsze
::bialko::bia³ko
::nieprawidlowe::nieprawid³owe
::hamuj¹ anabolizm::hamuj¹ katabolizm
::odzywiasz::od¿ywiasz
::bialek::bia³ek
::przygladaj¹c::przygl¹daj¹c
::efektywnoœc::efektywnoœæ
::zajrzec::zajrzeæ
::the lunch::lunch
::the breakfast::breakfast
::the home::home
::osiagniesz::osi¹gniesz
::porzucic::porzuciæ
::œwiadomoœc::œwiadomoœæ
::chcialalby::chciala³aby
::tasmowej::taœmowej
::kóra::kura
::ciezar::ciê¿ar
::powloki::pow³oki
::powlok¹::pow³oka
::widocznoœc::widocznoœæ
::pieknego::piêknego
::jakoœc::jakoœæ
::wyposazenia::wyposa¿enia
::niektorych::niektórych
::nieruchomosci::nieruchomoœci
::nieruchomoœc::nieruchomoœæ
::osi¹gnac::osi¹gn¹æ
::wyci¹gn¹c::wyci¹gn¹æ
::zacz¹c::zacz¹æ
::korzysci::korzyœci
::zamkn¹c::zamkn¹æ
::rózny::ró¿ny
::w³asnie::w³aœnie
::szczêscia::szczêœcia
::radosæ::radoœæ
::powstrzymac::powstrzymaæ
::uj¹c::uj¹æ
::tluszcz::t³uszcz
::przeciwslonecznych::przeciws³onecznych
::zacz¹³es::zacz¹³eœ
::cisnienie::ciœnienie
::wejœc::wejœæ
::rozmowca::rozmówca
::mi³oœc::mi³oœæ
::dr¹zku::dr¹¿ku
::elementow::elementów
::odwlekac::odwlekaæ
::patrza::patrz¹
::poczuc::poczuæ
::cie¿arów::ciê¿arów
::kilkanascie::kilkanaœcie
::zwiekszaæ::zwiêkszaæ
::wyjasnienie::wyjaœnienie
::chodz¹æ::chodz¹c
::siedz¹æ::siedz¹c
::ograniczen::ograniczeñ
::obci¹¿êniu::obci¹¿eniu
::dzialaæ::dzia³aæ
::oty³oœc::oty³oœæ
::opóxnienie::opóŸnienie
::zalecen::zaleceñ
::zwiekszenie::zwiêkszenie
::rozjasniæ::rozjaœniæ
::zdolnoœc::zdolnoœæ
::oty³oœc::oty³oœæ
::zajmujace::zajmuj¹ce
::podpi¹c::podpi¹æ
::pod³aczenie::pod³¹czenie
::g³oœnomowi¹cego::g³oœnomówi¹cego
::przeciwsloneczna::przeciws³oneczna
::g³oœnomowi¹cych::g³oœnomówi¹cych
::odchudzaj¹æe::odchudzaj¹ce
::schudnac::schudn¹æ
::schudnaæ::schudn¹æ
::przyj¹c::przyj¹æ
::dukana::Dukana
::dukana::Dukana
::montignaca::Montignaca
::obliczyc::obliczyæ
::dzieki::dziêki
::szczegoln¹::szczególn¹
::po³aczymy::po³¹czymy
::sk³onnoœc::sk³onnoœæ
::tydzien::tydzieñ
::zwiekszaj¹cy::zwiêkszaj¹cy
::funkjocnowania::funkcjonowania
::zwiekszania::zwiêkszania
::usun¹c::usun¹æ
::dostarczyc::dostarczyæ
::kalorycznoœc::kalorycznoœæ
::utrzymywac::utrzymywaæ
::dobrac::dobraæ
::wazniejszego::wa¿niejszego
::zwiazanych::zwi¹zanych
::lublinie::Lublinie
::uzupelniæ::uzupe³niæ
::plytek::p³ytek
::niiezaplacone::niezap³acone
::przysz³oœc::przysz³oœæ
::ma³zonków::ma³¿onków
::skoñczyc::skoñczyæ
::póxniejszej::póŸniejszej
::teksu::tekstu
::sprzedazowego::sprzeda¿owego
::róznymi::ró¿nymi
::wplywaj¹cym::wp³ywaj¹cym
::umiejêtnoœc::umiejêtnoœæ
::zapamietaj¹::zapamiêtaj¹
::zó³tej::¿ó³tej
::mowisz::mówisz
::dzia³a³es::dzia³a³eœ
::angazuje::anga¿uje
::iloœc::iloœæ
::obcia¿eniem::obci¹¿eniem
::zauwazyleœ::zauwa¿y³eœ
::zmieniac::zmieniaæ
::zamontowac::zamontowaæ
::wyd³u¿yc::wyd³u¿yæ
::tylem::ty³em
::informuja::informuj¹
::polegac::polegaæ
::imadlowym::imad³owym
::przek³amywac::przek³amywaæ
::podrózuje::podró¿uje
::czêsciom::czêœciom
::skutecznosci::skutecznoœci
::róznorodnych::ró¿norodnych
::trzymac::trzymaæ
::wieksza::wiêksza
::pomo¿ê::pomo¿e
::przeziebienia::przeziêbienia
::maœc::maœæ
::cie¿kich::ciê¿kich
::srodek::œrodek
::na³o¿yc::na³o¿yæ
::placiæ::p³aciæ
::gardla::gard³a
::sluz::œluz
::ciagu::ci¹gu
::sluzu::œluzu
::stawow::stawów
::rozluxnienie::rozluŸnienie
::przeszloœci¹::przesz³oœci¹
::po³ozyæ::po³o¿yæ
::zadziala::zadzia³a
::konska::koñska
::konsytencja::konsystencja
::oznaczajace::oznaczaj¹ce
::miêsniowe::miêœniowe
::kojarza::kojarz¹
::uczuc::uczuæ
::sza³wi::sza³wii
::dziase³::dzi¹se³
::nawil¿ajace::nawil¿aj¹ce
::czlowieka::cz³owieka
::narazonych::nara¿onych
::czêstotliwoœc::czêstotliwoœæ
::tansze::tañsze
::zdecydowac::zdecydowaæ
::s³uzyæ::s³u¿yæ
::elektrostatycznoœc::elektrostatycznoœæ
::pozwolic::pozwoliæ
::róznicê::ró¿nicê
::powazna::powa¿na
::doplaca::dop³aca
::doplata::dop³ata
::czêsciowa::czêœciowa
::¿o³adek::¿o³¹dek
::kandydowac::kandydowaæ
::pomozemy::pomo¿emy
::tluszczy::t³uszczy
::energetyzujace::energetyzuj¹ce
::slabsze::s³absze
::powaznych::powa¿nych
::wiêkszoœc::wiêkszoœæ
::kropelke::kropelkê
;2308
::ludxmi::ludŸmi
::ciala::cia³a
::zo³adek::¿o³¹dek
::wchlanianie::wch³anianie
::nieprawidlowa::nieprawid³owa
::wlaœciwoœci::w³aœciwoœci
::enzymow::enzymów
::zjeœc::zjeœæ
::ilosci::iloœci
::stsoowania::stosowania
::gramow::gramów
::glodu::g³odu
::odchudzajacych::odchudzaj¹cych
::tanca::tañca
::przejœc::przejœæ
::zaczyn¹j¹::zaczynaj¹
::przyjœc::przyjœæ
::stracic::straciæ
::bialkow¹::bia³kow¹
::obci¹zenie::obci¹¿enie
::po³aczenie::po³¹czenie
::masla::mas³a
::piêc::piêæ
::zmniejza::zmniejsza
::antyoskydantem::antyoksydantem
::koœcmi::koœæmi
::ogladaæ::ogl¹daæ
::objadac::objadaæ
::uchronic::uchroniæ
::komorki::komórki
::odpowiadaja::odpowiadaj¹
::przypisywac::przypisywaæ
::tloczonych::t³oczonych
::uzupelniaæ::uzupe³niaæ
::jakiegos::jakiegoœ
::makijarzu::makija¿u
::groxny::groŸny
::nadcisnienie::nadciœnienie
::æwiczenie::æwiczenie
::poczatkuj¹ce::pocz¹tkuj¹ce
::zdroiwe::zdrowie
::trafiaja::trafiaj¹
::utrzymac::utrzymaæ
::zupelnie::zupe³nie
::duzym::du¿ym
::spo³ecznosci::spo³ecznoœci
::wspólpraca::wspó³praca
::lamba::lambda
::moze::mo¿e
::jeset::jest
::nalezy::nale¿y
::bezpieczenstwo::bezpieczeñstwo
::g³êbokoœc::g³êbokoœæ
::cisnienia::ciœnienia
::œwiatel::œwiate³
::bezpieczeñtwa::bezpieczeñstwa
::najwazniejsze::najwa¿niejsze
::produków::produktów
::œwiezym::œwie¿ym
::daja::daj¹
::zaczêly::zaczê³y
::na³ozenie::na³o¿enie
::odzywianie::od¿ywianie
::produktow::produktów
::nieprawidlowego::nieprawid³owego
::prawidlow¹::prawid³ow¹
::nieprawidlowy::nieprawid³owy
::fitnesu::fitnessu
::cierpliwosci::cierpliwoœci
::doplywa::dop³ywa
::moze::mo¿e
::kamuflarzu::kamufla¿u
::kamuflarz::kamufla¿
::ziola::zio³a
::usun¹c::usun¹æ
::zaprezentowac::zaprezentowaæ
::nieprawidlow¹::nieprawid³ow¹
::moze::mo¿e
::wystepuje::wystêpuje
::miêsnie::miêœnie
::prawidlowe::prawid³owe
::zwiekszaniem::zwiêkszaniem
::dzialania::dzia³ania
::uprawiaja::uprawiaj¹
::mozgu::mózgu
::glowie::g³owie
::prawidlowy::prawid³owy
::planowac::planowaæ
::rozci¹niesz::rozci¹gniesz
::czulem::czu³em
::w¹tpliwosci::w¹tpliwoœci
::mówiac::mówi¹c
::angazowaæ::anga¿owaæ
::mêczyl::mêczy³
::tluszczowej::t³uszczowej
::skladników::sk³adników
::sennoœc::sennoœæ
::siedzialeœ::siedzia³eœ
;2406
::trzymaja::trzymaj¹
::najwiekszy::najwiêkszy
::rozwiazanie::rozwi¹zanie
::umiejêtnoœæi::umiejêtnoœci
::znajomoœc::znajomoœæ
::watroba::w¹troba
::zwiêrz¹t::zwierz¹
::zawartoœcia::zawartoœci¹
::produkujaca::produkuj¹ca
::wytrzyma³oœc::wytrzyma³oœæ
::œrodkow::œrodków
::odzywek::od¿ywek
::doswiadczonym::doœwiadczonym
::jakoœi¹::jakoœci¹
::jka::jak
::wspomagaj¹æe::wspomagaj¹ce
::piora::pióra
::dojœc::dojœæ
::œróby::œruby
::œróbami::œrubami
::œróbê::œrubê
::koñcowek::koñcówek
::faze::fazê
::osi¹gniêmy::osi¹gniemy
::jeœc::jeœæ
::slodzik::s³odzik
::przemyslany::przemyœlany
::stan¹c::stan¹æ
::skakac::skakaæ
::uksztaltowaæ::ukszta³towaæ
::zaanwansowania::zaawansowania
::ci¹glym::ci¹g³ym
::osi¹daj¹cych::osiadaj¹cych
::wnetrzu::wnêtrzu
::sprawdx::sprawdŸ

::bardz::bardzo
::ogl¹dac::ogl¹daæ
::dokanalowy::dokana³owy
::trwa³oœc::trwa³oœæ
::godizn::godzin
::g³osno::g³oœno
::prêdkosci::prêdkoœci
::wierzach::wie¿ach
::zapamietywanie::zapamiêtywanie
::wiezy::wie¿y
::g³owe::g³owê
::powiedziec::powiedzieæ
::wczesnie::wczeœnie
::produktow::produktów
::srodowisko::œrodowisko
::zastosownaia::zastosowania
::trwala::trwa³a
::permamentnego::permanentnego
::poœwiêcic::poœwiêciæ
::zablokowac::zablokowaæ
::poœwiêcic::poœwiêciæ
::odwiedzajace::odwiedzaj¹ce
::srodki::œrodki
::watrobê::w¹trobê
::wytrzymaloœciowe::wytrzyma³oœciowe
::doda³es::doda³eœ
::uci¹zliwe::uci¹¿liwe
::srodowisku::œrodowisku
::zwiekszone::zwiêkszone
::krwionosne::krwionoœne
::tlumaczem::t³umaczem
::zamkniete::zamkniête
::musialeœ::musia³eœ
::w³aczyæ::w³¹czyæ
::s³uzy::s³u¿y
::Uzywaj¹c::U¿ywaj¹c
::powiêkszyc::powiêkszyæ
::wyposazonego::wyposa¿onego
::sprawdzaja::sprawdzaj¹
::osi¹gniecie::osi¹gniêcie
::uwazny::uwa¿ny
::podrózujesz::podró¿ujesz
::przeznaczyc::przeznaczyæ
::uzytkowania::u¿ytkowania
::zlodziej::z³odziej
::s³uzyly::s³u¿y³y
::deskorolke::deskorolkê
::uniewersalne::uniwersalne
::Zwroæ::zwróæ
::jesli::jeœli
::poradzic::poradziæ
::usuwac::usuwaæ
::zniechêcac::zniechêcaæ
::zmywarke::zmywarkê
::programow::programów
::zmywarke::zmywarkê
::mieszcza::mieszcz¹
::g³osnymi::g³oœnymi
::kierowac::kierowaæ
::wytrzymaly::wytrzyma³y
::po¿adanego::po¿¹danego
::rozsypac::rozsypaæ
::wspominalismy::wspominaliœmy
::póxne::póŸne
::koœæi::koœci
::komorek::komórek
::w³¹czyc::w³¹czyæ
::watrobie::w¹trobie
::ziolowych::zio³owych
::nalezy::nale¿y
::pojedyñczych::pojedynczych
::pojedyñczych::pojedynczych
::ziolo::zio³o
::pacjentow::pacjentów
::ejst::jest
::Ÿródlem::Ÿród³em
::kupic::kupiæ
::odzywczy::od¿ywczy
::gêstoœc::gêstoœæ
::odróznianie::odró¿nianie
::lenth::length
::przycyzny::przyczyny
::wybierajac::wybieraj¹c
::ph::pH
::cie¿ej::ciê¿ej
::ca³osci::ca³oœci
::³¹twe::³atwe
::nawadniajace::nawadniaj¹ce
::œci¹gaj¹æe::œci¹gaj¹ce
::kapiele::k¹piele
::przek³¹da::przek³ada
::powiekszaj¹c¹::powiêkszaj¹c¹
::bezuzyteczne::bezu¿yteczne
::wodoszczelnoœc::wodoszczelnoœæ
::rzeczywistosci::rzeczywistoœci
::dziedzine::dziedzinê
::doswiadczenie::doœwiadczenie
::mia³¹::mia³a
::powloka::pow³oka
::³¹two::³atwo
::zabezpieczac::zabezpieczaæ
::zwiazki::zwi¹zki
::dzia³anai::dzia³ania
::podjaæ::podj¹æ
::s³ysza³es::s³ysza³eœ
::wlewac::wlewaæ
::goracej::gor¹cej
::jasniejsze::jaœniejsze
::cie¿k¹::ciê¿k¹
::niepotwarzalnym::niepowtarzalnym
::odczytac::odczytaæ
::wartoœæiowym::wartoœciowym
::niekorzyœc::niekorzyœæ
::nawilzenie::nawil¿enie
::radoœc::radoœæ
::istnieja::istniej¹
::kazda::ka¿da
::pewnoœcia::pewnoœci¹
::bêdizemy::bêdziemy
::dzialaniu::dzia³aniu
::polowac::polowaæ
::znajduja::znajduj¹
::wyróznia::wyró¿nia
::zastapiony::zast¹piony
::jakoœæi::jakoœci
::mieœæi::mieœci
::zasadowoœc::zasadowoœæ
::wodoodpornoœc::wodoodpornoœæ
::funtion::function
::skonsultowac::skonsultowaæ
::rózniæ::ró¿niæ
::prêdkosæ::prêdkoœæ
::spowodowac::spowodowaæ
::plazy::pla¿y
::sk³adaja::sk³adaj¹
::tresci::treœci
::zasiegu::zasiêgu
::zastanowic::zastanowiæ
::odbiorcow::odbiorców
::reklamowac::reklamowaæ
::sluchu::s³uchu
::kupilem::kupi³em
::potrzebowal::potrzebowa³
::wygladem::wygl¹dem
::odbieraja::odbieraj¹
::kreatywnoœc::kreatywnoœæ
::Kreatywnoœc::Kreatywnoœæ
::rekê::rêkê
::ogladac::ogl¹daæ
::dosæ::doœæ
::ul¹twi::u³atwi
::czcionke::czcionkê
::slowa::s³owa
::wybieralem::wybiera³em
::musialem::musia³em
::watroby::w¹troby
::narazone::nara¿one
::¿ywnoœæi::¿ywnoœci
::zwyklych::zwyk³yhc
::spo³ecznosciowym::spo³ecznoœciowym
::stopien::stopieñ
::wynikac::wynikaæ
::bêda::bêd¹
::kumuluja::kumuluj¹
::schowac::schowaæ
::kupowac::kupowaæ
::Bezsennoœc::Bezsennoœæ
::mia³es::mia³eœ
::ci¹zy::ci¹¿y
::postawic::postawiæ
::smieræ::œmieræ
::brzmiec::brzmieæ
::wykorzystac::wykorzystaæ
::czesto::czêsto
::odró¿nic::odró¿niæ
::przedsiebiorcy::przedsiêbiorcy
::okreslenie::okreœlenie
::doraxnie::doraŸnie
::m¹ke::m¹kê
::estrogenow::estrogenów
::ustabilizowac::ustabilizowaæ
::unormowac::unormowaæ
::Dziêki nim, mo¿na::Dziêki nim, mo¿na
::stanow::stanów
::pomidorow::pomidorów
::z³ozone::z³o¿one
::weglowodany::wêglowodany
::rzucia::¿ucia
::odzywiamy::od¿ywiamy
::odzywia::od¿ywia
::owocow::owoców
::wysokosci::wysokoœci
::interesujace::interesuj¹ce
::pobudzajacego::pobudzaj¹cego
::stosujac::stosuj¹c
::trendow::trendów
::roslinnego::roœlinnego
::g³osnoœci::g³oœnoœci
::dŸwiekow::dŸwieków
::midi::MIDI
::dópa::dupa
::jakosc::jakoœæ
::kontaktowac::kontaktowaæ
::przenosne::przenoœne
::wirusow::wirusów
::funkcjonalnosci::funkcjonalnoœci
::wyposazonych::wyposa¿onych
::smartfonow::smartfonów
::bolem::bólem
::uzytkowniczek::u¿ytkowniczek
::cierpien::cierpieñ
::wiekszoœæ::wiêkszoœæ
::wybor::wybór
::widht::width
::planetanych::planetarnych
::dlugoœæ::d³ugoœæ
::uzywanego::u¿ywanego
::ktorymi::którymi
::u³ozone::u³o¿one
::domow::domów
::odlegloœci::odleg³oœci
::bezworkowe::bezworkowe
::narazony::nara¿ony
::sprzetem::sprzêtem
::mysleæ::myœleæ
::zwiekszenia::zwiêkszenia
::0px::0
::otrzymuja::otrzymuj¹
::schudla::schud³a
::slowa::s³owa
::g³ebokich::g³êbokich
::dlugotrwa³e::d³ugotrwa³e
::mi³osników::mi³oœników
::obliczen::obliczeñ